### ISSUE TITLE
Create static k8s manifests for scaled deployment

### ISSUE THREAD

**Issue by themightychris** [CodeForPhilly/chime#1]
For our first pass at providing an alternative to Heroku, we've spun up a dedicated `chime-live` Kubernetes cluster on Linode. Currently it has 3 nodes with 6 CPUs each

To close this issue, add a set of static manifests to this repository for a deployment that takes the *current* Streamlit-based Chime implementation, runs as many workers as possible on that 3x6 cluster, and includes deploying an in-cluster ingress controller that will load balance between all those workers and serve out of `penn-chime.phl.io`

Skip any templating or automation at this phase, we'll manually deploy the manifests and manually edit them as needed. After we learn more, we'll create follow-up issues around templating or automation

**Comment by sam-qordoba** [comment]
"as many workers as possible on that 3x6 cluster" do we know how many CPUs are left after k8s + ingress overhead? I assume around 15? Since Python is so single-threaded, probably just want to run 15 (+/- a few) replicas?

**Comment by themightychris** [comment]
@sam-qordoba that sounds like a reasonable assumption to start from, and then adjust as needed

**Comment by asauber** [comment]
Hi. I work on Kubernetes infrastructure at Linode, and have quite a bit of experience with Ingress and dynamically scaling Kubernetes clusters.

Per an internal discussion, we would like to help you guys out here with what you need!

Any chance you can hop on a call at 8:30pm EST tonight? 
What's a good email address to reach you for an invite?

**Comment by asauber** [comment]
Also, I'm the author of the `linode-cli k8s-alpha` plugin. Out of curiosity, is that what you used to deploy your current cluster?

**Comment by themightychris** [comment]
Hey @asauber , thanks for connecting! I can jump on a call at 8:30, hop into our slack workspace if you can: http://codeforphilly.org/chat/chime-ops

**Comment by themightychris** [comment]
We've got a working cluster up at http://lke.penn-chime.phl.io/ so I think this one is  done
