### ISSUE TITLE
The tool should not crash when the confirmed cases=0 and/or hospitalization=0

### ISSUE THREAD

**Issue by sam-qordoba** [CodeForPhilly/chime#10]
There should be either instruction to use "1" instead of "0", or update the code to use 1 when someone enters 0.

currently the tool crashes.

![image](https://user-images.githubusercontent.com/47401552/76886863-98db6e80-683e-11ea-81a6-f7d730d297c8.png)

**Comment by quinn-dougherty** [comment]
I can't get ubuntu screenshots to capture it, but a warning pops up preventing `hospitalizatiions` from being zero. 

Currently Known Regional Infections = 0 does not crash the app.
