### ISSUE TITLE
Error when social distancing is set to 100%

### ISSUE THREAD

**Issue by garysieling** [CodeForPhilly/chime#103]
```ZeroDivisionError: float division by zero
Traceback:
  File "/usr/local/lib/python3.7/site-packages/streamlit/ScriptRunner.py", line 314, in _run_script
    exec(code, module.__dict__)
  File "/app/app.py", line 141, in <module>
    r_naught = r_t / (1 - relative_contact_rate)
```

**Comment by sam-writer** [comment]
![image](https://user-images.githubusercontent.com/47401552/77110927-9e25ee00-69e3-11ea-8265-5557af831ba6.png)

Fixes:
* prevent the user from entering 100 in this field, set the max to 99.9 or 99.99
* fix the math to prevent division by zero

**Comment by quinn-dougherty** [comment]
i piggybacked this in https://github.com/CodeForPhilly/chime/pull/143
