### ISSUE TITLE
Fix https://codeforphilly.github.io/chime/CONTRIBUTING.html to reflect new PR process

### ISSUE THREAD

**Issue by josh-bluewater** [CodeForPhilly/chime#109]
Doc currently shows older info requesting contributers to 
* "Base all work on the latest master branch available in Code for Philly's fork of the chime repository.
* Submit your work in the form of a pull request against that same branch."

**Comment by themightychris** [comment]
This was recently fixed in #100 and will be reflected in the published docs after we merge #95
