### ISSUE TITLE
admitted patients (census) chart is weekly granular, should be daily 

### ISSUE THREAD

**Issue by quinn-dougherty** [CodeForPhilly/chime#11]
as per discussion in thread https://github.com/pennsignals/chime/pull/58 ,

it used to look like this 
![76877593-0640cc80-684a-11ea-89ab-f5b1e7e2f279](https://user-images.githubusercontent.com/39039420/76886881-c7197800-6857-11ea-8ed6-de905822b822.png)

now it looks like this
![Screenshot from 2020-03-17 12-55-14](https://user-images.githubusercontent.com/39039420/76886900-d13b7680-6857-11ea-9b3e-587aeda3838e.png)

the granularity of the chart should be daily, not weekly, this detail has to be recovered from the matplotlib version.

**Comment by MooseQuest** [comment]
Add accessibility to this chart and allow for the granularity to be selected. If there is argument against, we'd probably need to explain why the data is daily | weekly.
