### ISSUE TITLE
Update model parameters

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/chime#112]
Update model calls to use parameters from Defaults and Parameters instead of the original global variables. The Defaults and Parameters objects are from #111 and #110 

Done: 
 - "model.\*" object that holds DataFrames output from the Models rather than passing multiple pieces of related information (ei. s, i, and r vectors).
 - Feed "control.\*" and "model.\*" into the Charts, Have the Charts produce properties of a "view.\*" object that can be unit tested. Usually a projection of a model or model(s) DataFrames. Separate Chart render from the 'view.\*' for unit testing.

**Comment by quinn-dougherty** [comment]
update: model will not be a _class_, it will be a _function_ signed `Parameters -> DataFrame`. The Parameters object is defined in https://github.com/CodeForPhilly/chime/pull/154 models.py

**Comment by jlubken** [comment]
Sounds good to me!

**Comment by quinn-dougherty** [comment]
https://github.com/CodeForPhilly/chime/pull/182
