### ISSUE TITLE
Render with new objects

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/chime#114]
done: Have a render that takes default, control, model and view objects

Depends on #112

**Comment by machow** [comment]
(Copying here from slack channel, in case streamlit and dash examples are useful. )

I would caution against adding render functions, for two reasons:

* they are largely dashboard library specific
* in many libraries the render part is very simple to specify

For example, in streamlit, using PR #106, the render is two lines of non-streamlit code, and 2 lines of streamlit...

```python
from penn_chim.components import EstimateNewAdmissions
<Bunch of InputWidgets>        # note: streamlit specific
est = EstimateNewAdmissions(<bunch of input widget crnt vals>...)
p = est.plot_new_admissions()
st.write(p)                    # note: streamlit specific
```

In dash the server side render might be something like...

```python
@app.callback(
    Output('indicator-graphic', 'figure'),    # note: may need tweaking for altair plots
    [
        Input(component_id='some-input1', component_property='value'),
        Input(component_id='some-input2', component_property='value'),
        ...   # etc for all inputs
    ]
)
def update_output_div(input1_val, input2_val):
    est = EstimateNewAdmissions(input1_val, input2_val, ...)
    p = est.plot_new_admissions()
    some_dash_builtin_render_function(p)    # in this case, for altair plots
```

So if...

* the render is dashboard-agnostic, then it is two simple lines (eg documented in the class).
* the render is not dashboard-agnostic, then it's likely it will only be used once (in the dashboard), so may be useful to just keep in there, so people need to do less jumping around

**Comment by quinn-dougherty** [comment]
I think that this issue can't be done in a dashboard-agnostic way. 

edit: i flatly can't imagine how rendering could _possibly_ be done in a platform-agnostic way.

**Comment by quinn-dougherty** [comment]
I feel like we've done as much as we can. @jlubken  let me know if you'd like to see anything else from this issue, otherwise we'll close it

**Comment by quinn-dougherty** [comment]
spurred by @machow 's idea
```python
class EverythingWrapper: 
   def __init__(self, parameters: Parameters): 
      self.parameters = parameters
      self.admissions_df = admissions_df(parameters)
      self.census_df = census_df(parameters)
      self.admissions_chart = admissions_chart(self.admissions_df)
      self.census_chart = census_chart(self.census_df) 
```
