### ISSUE TITLE
Unit test new SimSirModel object

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/chime#115]
Add unit tests for SimSirModel object

**Comment by mariekers** [comment]
Include manual tests done by Penn:

1.     Open up the live (production) app at http://penn-chime.phl.io/
2.     Refresh the page to make sure no inputs are cached
3.     In a second tab/window run the app locally (e.g. http://127.0.0.1:8000/)
4.     Verify one by one that each of the inputs in the sidebar have not moved (unless this was an explicit part of the issue being addressed). If the issue changed the input on purpose, make sure the rest of the inputs are in the same order as they were before
5.     Line up the main frame of the app (the right hand side)
6.     Go through the live and local version of the app one page at a time, keeping them in line so you can easily see if there are differences.
7.     Click all the check boxes and carefully inspect that the results are the same
8.     Look at all graphs and verify that the scale on the y-axis matches and that the scale on the x-axis matches. Verify that the values match
9.     Look at each of the data tables and verify that the data in the matches
10.     Pay special attention to the bold numbers at the top of the app and the various numbers in “Show more info about this tool” section near the top
11.     Change the values for “Currently Hospitalized COVID-19 Patients”, “Doubling time before social distancing (days)” and “Number of days to project” (slider on the right hand panel) to new values.
12.     Make sure these values are exactly the same in both the live (production) app and in the local app
13.     Repeat steps 3-5
14.

**Comment by quinn-dougherty** [comment]
> Include manual tests done by Penn: 

this is the subject of a different kind of testing, at least the way i'm currently interpreting this issue.

**Comment by quinn-dougherty** [comment]
pending https://github.com/CodeForPhilly/chime/pull/208 getting merged

**Comment by pjhoberman** [comment]
It looks like this model already has a unit test around it: https://github.com/CodeForPhilly/chime/blob/7b8e6e504e3a68043ce930955dcaa49169c24f74/tests/test_app.py#L224

Is there more to the unit test, or is the request here to set up a selenium-style test for the manual tests listed here: https://github.com/CodeForPhilly/chime/issues/115#issuecomment-601438650
