### ISSUE TITLE
Self-host CSS file

### ISSUE THREAD

**Issue by themightychris** [CodeForPhilly/chime#118]
The app currently embeds a hotlink to `https://www1.pennmedicine.org/styles/shared/penn-medicine-header.css`

Could we copy the needed bits of this into the project and hosted it out of `/static/` somehow so we're not hitting pennmedicine.org from every instance we run?

**Comment by kmid5280** [comment]
@themightychris I'd be happy to give this one a try.

**Comment by themightychris** [comment]
@kmid5280 our initial research for #107 determined this probably isn't office t to do application-side under streamlit, it sounds like we'd need to do something at the load balancer level

Streamlit _might_ get replaced soon so it's probably best to give that effort a couple days to pan out before putting in too much work on a workaround

**Comment by quinn-dougherty** [comment]
this is doable in Dash

**Comment by quinn-dougherty** [comment]
@welfare is working on this
