### ISSUE TITLE
Update viz package

### ISSUE THREAD

**Issue by sam-qordoba** [CodeForPhilly/chime#12]
* Replace matplotlib with interactive viz package (altair, plotly, etc) to speed up app delivery and improve interactivity
* replace visualizations with new package code
* Another factor to consider is the amount of space each input (e.g. Currently Known Regional Infections, Currently Hospitalized COVID-19 Patients) takes up. It would be nice to be able to use the screen space more efficiently to minimize scrolling and fit other informative text/data. The current fix is to hide additional text/data behind checkbox toggles.

See https://github.com/pennsignals/chime/pull/58

CC @quinn-dougherty

**Comment by quinn-dougherty** [comment]
i think we can close this. https://github.com/pennsignals/chime/pull/58 is merged. and there's some followup in the form of https://github.com/pennsignals/chime/issues/29 and https://github.com/CodeForPhilly/chime/issues/11 

To the comment about the sidebar UX--- 
1. streamlit is very limited, it hides all the css from us so we can't manipulate those elements at all
2. the sidebar can be hidden-- there's a little `x` button in the corner. I hope this helps
3. in general this comment can be broken out into it's own issue
