### ISSUE TITLE
Templates and docs for Operations Procedures

### ISSUE THREAD

**Issue by MooseQuest** [CodeForPhilly/chime#129]
Will need to outline where to put After Action Review(s) (AAR) for production issues, and what runbooks are needed to resolve issues quickly.

**Comment by lottspot** [comment]
Some procedures to document:

* Falling back to Heroku
* Rolling back a production release
* Resolving certificate issues (?)

**Comment by MooseQuest** [comment]
The certificate issues should explain how the certs I guess "work" but also how to ensure the right domain is pointed on the host. We patched, but never put it back in the documentation. @asauber (slack) I think PR'ed that last night.

**Comment by asauber** [comment]
Here's some documentation on how to add some flexibility during a cutover in the form of code. https://github.com/CodeForPhilly/chime/pull/148

**Comment by rcknplyr** [comment]
Closing this in this repo. Marked with 'future' label. Let's address in Chime2.0 repo
