### ISSUE TITLE
Add CI tool for testing

### ISSUE THREAD

**Issue by sam-qordoba** [CodeForPhilly/chime#13]
Potential goals, from slack conversation:

1. Goal - make sure the Penn version of this is easy to deploy
2. Goal - make sure this is easy for new places to adopt

Some potential next steps (pulled from slack discussion):

1. Hook up Github actions
2. Document workflow for tagging releases
3. Document workflow to prove site has deployed
4. Script & document this workflow: fork the repo, spin up a commodity k8s cluster anywhere, drop a kubeconfig into GH Actions Secrets, and have an automated deploy-on-tag flow going

**Comment by sam-qordoba** [comment]
The plan is to push the docker image to dockerhub, https://hub.docker.com/orgs/codeforphilly - that should maybe be part of CICD

**Comment by mariekers** [comment]
are we using github actions for this?

**Comment by mariekers** [comment]
the goals here are really to 

- [ ] have a CI tool that checks PRs 
- [ ] implement the tool on this repo
- [ ] leverage github actions
