### ISSUE TITLE
Update heroku version

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/chime#138]
Done: heroku version is up to date

**Comment by rcknplyr** [comment]
Hi @mariekers, from your comment above, it appears this issue is resolved. If you agree, please let me know I will close it. Thanks

**Comment by mariekers** [comment]
@themightychris I think this was from a comment made in the devops channel - I'm guessing heroku was updated?

**Comment by themightychris** [comment]
Our automation updates the new staging heroku site from `develop`, but we don't currently cover updating Penn's original heroku account from releases. It could, but currently I believe that's still being done manually by Penn's team so it may be out of date

**Comment by mariekers** [comment]
I think that covers the initial ask - I'll close this
