### ISSUE TITLE
Add caching

### ISSUE THREAD

**Issue by sam-qordoba** [CodeForPhilly/chime#14]
streamlit supports caching... maybe this would be a good idea to speed things up?

[Streamlit caching docs](https://docs.streamlit.io/caching.html)

**Comment by quinn-dougherty** [comment]
This will follow trivially from wrapping key operations in functions as discussed here https://github.com/pennsignals/chime/issues/6#issuecomment-600214043 -- note caching is not the sort of side effect that limits modularity in my experience.
