### ISSUE TITLE
Allow users to fix y-axis

### ISSUE THREAD

**Issue by Mdraugelis** [CodeForPhilly/chime#145]
To enable reporters to compare scenarios they need to be able to fix the y and x axis.

**Comment by nickcanz** [comment]
@Mdraugelis could you provide a little more detail? I'm guessing this means the ability to set a max Y value to a number that they input. Should it be one input that goes across all the graphs?

**Comment by quinn-dougherty** [comment]
@nickcanz  i think setting max y value makes sense. 

please add an `int` to the chart function input that's defaulted `None`, and if it isn't None when you `.encode(` pass in `y=alt.Y('<column>', scale=alt.Scale(max=<int> ` something like this
