### ISSUE TITLE
Users should be able to toggle between days and dates that appear in graphs and tables

### ISSUE THREAD

**Issue by Mdraugelis** [CodeForPhilly/chime#147]
The user should be able to enter in the day 0.  Not necessarily the current day.  This will allow teams to understand their past projects as well as understand where they are in the curve.

Some users want to communicate day zero plus a number of days and some users want dates.

For Penn Medicine internal leadership only wants to see dates. This then requires the analyst to translate the days into dates.

**Comment by mariekers** [comment]
Is this duplicated in #56 ?  I can close that one if so

**Comment by Mdraugelis** [comment]
Good catch @mariekers .  I would add an additional user need.  Can you close the other #56  task?

**Comment by ckoerber** [comment]
It seems to me that the including this feature can be realized in a straightforward way by adding a `date` column to used data frames, e.g.,
```python
from datetime import datetime

df["date"] = pd.date_range(
    datetime.now(),
    periods=projection_admits.shape[0],
    freq="D"
)
```
where adjusting `datetime.now()` could in principle be replaced with an arbitrary string (and some date shift logic which requires data-time awareness).

I am uncertain, where it might be most useful to include this: 

1. Either one might add the new column just within the drawing functions in `penn_chime.presentation.py`. This would mean one has to add the date column in each drawing function. 
2. Or, alternatively, one could add this in the  `penn_chime.utils.py` function (possibly changing later behavior which uses wildcards for columns as l.29 `build_census_df`).

I have an example implementation for (1) [in my fork](https://github.com/CodeForPhilly/chime/compare/develop...ckoerber:feature-present-as-date). If this is what you expect, and depending on which scenario is more desirable, I can create a PR. 

![Screen Shot 2020-03-20 at 21 40 38](https://user-images.githubusercontent.com/35035055/77204650-7c1b9100-6af3-11ea-824c-61b29d2ccc68.png)

**Comment by quinn-dougherty** [comment]
thanks @ckoerber . I have no preference whether you put it in the func `-> Chart` or the func `-> DataFrame`. But unless you can verify there are no bugs anywhere in the chain putting it in `build_census_df`, go for putting it in `presentation.py`.

**Comment by ckoerber** [comment]
PR is out. Let me know if this matches expectations.

**Comment by quinn-dougherty** [comment]
> The user should be able to enter in the day 0. Not necessarily the current day. This will allow teams to understand their past projects as well as understand where they are in the curve.

This is a different issue than 147's issue name. 

i filed https://github.com/CodeForPhilly/chime/issues/168 for this.
