### ISSUE TITLE
Support Interventions

### ISSUE THREAD

**Issue by sam-qordoba** [CodeForPhilly/chime#15]
Given that many governments are enacting policies which effectively change R0, it might be useful to support an "intervention" - a sudden change in R0.

**Comment by sam-qordoba** [comment]
The current workaround is described in [this slack convo](https://codeforphilly.slack.com/archives/CV4NGQYMP/p1584486248206800):

> Is it reasonable to adjust the doubling time to simulate different levels of intervention success?
> Yes, for now that is the lever to pull to simulate reductions in contact rates.

**Comment by cjbayesian** [comment]
We built in a first pass at this upstream in https://github.com/pennsignals/chime/pull/70. It should be integrated now.

**Comment by PhilMiller** [comment]
Single-date intervention is now implemented, pending just addition to the newer Dash UI #459. There's a potential longer-range plan of allowing input of successive interventions (or relaxations . . .). The model code is already set up to handle, and even fit consistent values for, that series, whenever UI is added for it.
