### ISSUE TITLE
Refactor presentation functions

### ISSUE THREAD

**Issue by jlubken** [CodeForPhilly/chime#158]
Cleanup presentation functions to use Parameters object (p) instead of the bucket-o-parameters lists that will be difficult to maintain.

Add type annotation to the functions, so that editors/linters/ide notice discrepancies between the Parameters class definition and the properties used in each renderer.

Wait for #157

**Comment by quinn-dougherty** [comment]
closed https://github.com/CodeForPhilly/chime/pull/182
