### ISSUE TITLE
new file tree

### ISSUE THREAD

**Issue by quinn-dougherty** [CodeForPhilly/chime#167]
tree should be 
```
penn_chime/
| -app.py
| -test_app.py
| penn_chime/
  | -models.py
  | -presentations.py
  | ...
```

**Comment by themightychris** [comment]
Could the first one be `src/` ?

**Comment by quinn-dougherty** [comment]
maybe. i'm deferring to @sam-qordoba based on a discussion we had about this. 

if we eventually want the backend to be pip-installable, the tree i listed is better

**Comment by quinn-dougherty** [comment]
nvm, first one is gonna be `src`
