### ISSUE TITLE
The user should be able to enter in the day 0. Not necessarily the current day. 

### ISSUE THREAD

**Issue by quinn-dougherty** [CodeForPhilly/chime#168]
> This will allow teams to understand their past projects as well as understand where they are in the curve.

**Comment by mdbecker** [comment]
Hey @quinn-dougherty let's chat about this, I think this was a miscommunication.

**Comment by quinn-dougherty** [comment]
there is a tradeoff between more options and more cluttered UI that should be considered.

**Comment by cjbayesian** [comment]
Working on a solution. linking #255

**Comment by jlubken** [comment]
Fixed with the last merge of issue 255
