### ISSUE TITLE
Add CHIME to helpwithcovid.com

### ISSUE THREAD

**Issue by mdbecker** [CodeForPhilly/chime#181]
We're not on https://helpwithcovid.com/projects?query=

Add CHIME to the list of projects.

**Comment by quinn-dougherty** [comment]
Can this wait? i think in a few days our PMing and codebase will be in a better spot to handle the influx of volunteers. 

i'm on a helpwithcovid.com project when i'm not working on this, and it's slammed at like 15 new participants per day --- it's good for some projects, but not where we're at at the moment. 

i think this should be reopened when we're off streamlit

**Comment by quinn-dougherty** [comment]
ok i'm recommending we do this now. call for volunteers should be explicitly about Plotly Dash, but i don't know who else we need

**Comment by mariekers** [comment]
https://helpwithcovid.com/projects/363-covid-19-hospital-impact-model-for-epidemics-chime-app

**Comment by mishmosh** [comment]
@mariekers is there a way to add an explicit call for Python Dash experience?

**Comment by mariekers** [comment]
@mishmosh done
