### ISSUE TITLE
we claim that it can run on python2 but we use keyword-only arguments

### ISSUE THREAD

**Issue by quinn-dougherty** [CodeForPhilly/chime#186]
keyword-only arguments in parameters.py. keyword-only arguments are a python3 feature. 
```
    def __init__(
        self, *,
        current_hospitalized: int,
```

in docs we claim python 2.7 is viable https://github.com/CodeForPhilly/chime/blob/develop/docs/contributing/app-dev.md 

**in favor of keeping keyword-only arguments and dropping python2.7** 
- we like keyword-only arguments
- python2.7 is officially over, technically
- anyone using the CLI or running locally can handle setting up a python3 environment

**in favor of dropping keyword-only arguments and keeping python 2.7**
- people have python27 as the default on their machine. 
- some of these people may benefit from the CLI 

*a further problem is that the CLI isn't documented yet.*

**Comment by themightychris** [comment]
FWIW, I copy+pasted that requirement info from Streamlit's docs with no intention or understanding of the implications

**Comment by mariekers** [comment]
so the ticket should be updating the docs stating that the app requires python 3.7 (it's a requirement in the pipfile) ?

**Comment by sam-writer** [comment]
We use types pretty heavily, which IIRC are a 3.6+ feature. So, either we have to strip them from the code, which is a cost both in time, and in our ability to get good feedback from our editors when developing, or update the docs to say "this requires python 3.6+, and is tested on Python 3.7 and 3.8"

I say those version bc our Docker image uses 3.7 https://github.com/CodeForPhilly/chime/blob/develop/Dockerfile#L1
and GH Actions uses 3.8 https://github.com/CodeForPhilly/chime/blob/develop/.github/workflows/pythonapp.yml#L24

So I think this should be an "update docs" ticket
