### ISSUE TITLE
Fix calculation of daily new infections

### ISSUE THREAD

**Issue by cjbayesian** [CodeForPhilly/chime#189]
Current daily new infections are being calculated as $I_{t+1} - I_{t}$, which doesn't account for the infected cases transitioning into recovered during that time step. The calculations should be $I_{new} = (I_{t+1} - I_{t}) + (R_{t+1} - R_{t})$

**Comment by cjbayesian** [comment]
https://github.com/CodeForPhilly/chime/blob/7f7e33e2605ff280a100cd4eb4c69684ffba9725/src/penn_chime/models.py#L88

**Comment by cjbayesian** [comment]
Not apples to apples, but here is the fixed output on the pre-refactored code:
![image](https://user-images.githubusercontent.com/1396669/77268363-03940c00-6c7c-11ea-83cd-4f47ed9174e5.png)

**Comment by cjbayesian** [comment]
Working on getting the fix implemented on refactored code.

**Comment by PhilMiller** [comment]
Please add the 'models' label to this, so I can link to https://github.com/CodeForPhilly/chime/labels/models in the app header, and have it reflect the list of changes
