### ISSUE TITLE
Enforce black

### ISSUE THREAD

**Issue by mdbecker** [CodeForPhilly/chime#193]
Setup [black](https://github.com/psf/black) for the repo to keep all the code properly formatted. I'm not sure if this is something we can do with Actions but if so that might be desirable. 

Refactor source file a few at a time to avoid huge merge conflicts.

**Comment by grahamalama** [comment]
https://github.com/CodeForPhilly/chime/pull/420 was merged, which adds black to the Lint and Test workflow, but it's set to [`continue-on-error`](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepscontinue-on-error) for now. We should take this `continue-on-error` out at some point when we decide to format the whole codebase.
