### ISSUE TITLE
Tabular values of charts should show daily values.

### ISSUE THREAD

**Issue by jordanclark397** [CodeForPhilly/chime#207]
Currently, the option to show tabular values for the new admissions and census figures only provide values every seventh day (day 0, 7, 14, etc.). This is useful for recreating charts, but not for estimates at a more granular level (e.g., 3 days from today). It would be useful to have an option to see tabular values for each day on the plot (day 0, 1, 2, 3, 4, 5, etc.).

**Comment by mariekers** [comment]
Would it be possible to add a toggle function on the tabular data to get daily counts?

**Comment by jordanclark397** [comment]
@mariekers That would be ideal for us. Even just a separate page with a blob of comma-separated numbers would be great. Something that can quickly be copy-pasta'd into excel.

**Comment by kmid5280** [comment]
@jordanclark397 What about adding a slider bar that would set the number of days?

**Comment by quinn-dougherty** [comment]
https://github.com/CodeForPhilly/chime/pull/209 closed by this. i don't actually know why Nick's PR closeed this.
