### ISSUE TITLE
Normalize COVID-19 data from Seattle (or Washington)

### ISSUE THREAD

**Issue by sam-qordoba** [CodeForPhilly/chime#21]
Find the published source and normalize for https://docs.google.com/spreadsheets/d/1P1W6nLPYPoIqKmvKJWq1iUCkTsrPOu7DkOMTmWotJik/edit?usp=sharing

**Comment by mdbecker** [comment]
Hey @sam-qordoba I'm not sure I understand the intent of this ticket. Could you elaborate?

**Comment by sam-writer** [comment]
hmmm the old penssignals issues are gone, so I can't point you to the original reporter... this was just from that time when I copied over all the old issues, so I actually don't know the point.

**Comment by rcknplyr** [comment]
@sam-qordoba and @mdbecker Planning to close this issue - let me know if any objections.
