### ISSUE TITLE
Conflation of regional population with susceptible population is wrong with large infection count

### ISSUE THREAD

**Issue by PhilMiller** [CodeForPhilly/chime#211]
The raw data shows a total of S+I+R that is larger than the user-provided regional population. This is because the number presumed initially infected based on hospitalization rate isn't subtracted from the population to compute the currently susceptible.

**Comment by PhilMiller** [comment]
I'll fix this

**Comment by mariekers** [comment]
@quinn-dougherty is the reformatted app base in the develop branch?  
@PhilMiller if you're working on it - mind doing the updates in the new codebase?

**Comment by quinn-dougherty** [comment]
@mariekers @PhilMiller @jlubken just glanced at the `pull/212` diff, there will be conflicts with `pull/208` 

212 renames `susceptible` to `population` in `parameters.py`

**Comment by quinn-dougherty** [comment]
still don't know which one of those will get merged in first.

**Comment by PhilMiller** [comment]
Move #208 ahead. As noted, #212 requires some more thought, and possible re-design. I'll eat the minimal merge effort.
