### ISSUE TITLE
When showing dates (instead of #days), the x-axis labels are a combination of Month-Day and DayOfWeek-Day

### ISSUE THREAD

**Issue by therealthaibinh** [CodeForPhilly/chime#213]
This is with current page defaults, and with "Present result as dates instead of days" checked.
![image](https://user-images.githubusercontent.com/3888147/77370626-aeb5cb80-6d37-11ea-8e8e-03a6c206776a.png)

**Comment by kmid5280** [comment]
What would you prefer to have? Just to show the days only, i.e. "Wed 25?"

**Comment by therealthaibinh** [comment]
Ideally, the month and the day (e.g. "Mar 25"), like in the original issues:
https://github.com/CodeForPhilly/chime/issues/147#issuecomment-601902288
https://github.com/CodeForPhilly/chime/pull/165#issuecomment-602045243

**Comment by kmid5280** [comment]
It looks like the value for DATE_FORMAT, line 13 in src/penn_chime/presentation.py is not getting passed in properly to the date_format conditional on line 54, src/penn_chime/utils.py, or that conditional is not being triggered. I can set that value to anything and it won't change the output.

**Comment by kmid5280** [comment]
I also tried canceling out the ampersands in the DATE_FORMAT value using backslashes, i.e. `DATE_FORMAT = "%\b, %\d"` without any success.

**Comment by mariekers** [comment]
Would this be fixed in the plotly switchover?
