### ISSUE TITLE
Cypress intermittently times out

### ISSUE THREAD

**Issue by garysieling** [CodeForPhilly/chime#214]
Reported through slack - sometimes this step fails, but will pass on re-execution

e.g. https://github.com/CodeForPhilly/chime/pull/191/checks?check_run_id=528505109

**Comment by MooseQuest** [comment]
@garysieling Do you have an update on this, might try to pull in additional resources to debug.

**Comment by garysieling** [comment]
Yeah, it looked like it's an issue once the test is running in Cypress (i.e.. the page not loading correctly all the time) rather than a timeout with it starting up. If someone else has time to look that's fine by me

**Comment by MooseQuest** [comment]
Might need a more customized approach. I don’t know much about Cypress so maybe I’ll take the time to learn.

-Kristerpher

**Comment by MooseQuest** [comment]
Going to investigate this again; reopening.

**Comment by rcknplyr** [comment]
Looks like this has not happened recently. Closing for now.
