### ISSUE TITLE
Toggle linear/log scaling of y-axes on plots

### ISSUE THREAD

**Issue by sam-qordoba** [CodeForPhilly/chime#22]
@quinn-dougherty added a bool flag to functions that look like `def some_chart(*args) -> alt.Chart:`. if `logscale` is flagged, do something like `.encode(y=alt.Y("col", scale=alt.Scale("log")`
 ... read the docs for specific syntax.

**Comment by sam-qordoba** [comment]
There is an open PR for this in the old repo, https://github.com/pennsignals/chime/pull/39

**Comment by quinn-dougherty** [comment]
sorry, didn't actually add a flag to the function! i was writing a suggestion to someone who might take this card, not noting what i already did

it's definitely possible
- add the flag to function signature
- handle flag in function body
- you can ask the user at function calltime for their preference, if you do this in the simplest possible manner streamlit will put it directly above the chart in control flow.
