### ISSUE TITLE
["bug"] Weird graphing glitch when setting "Y-axis static value"

### ISSUE THREAD

**Issue by mdbecker** [CodeForPhilly/chime#228]
### Description:
Weird graphing glitch when setting "Y-axis static value". Fortunately this just appears to be a display glitch and is not impacting the underlying data in any way. 

### Steps to reproduce:
1. Set "Y-axis static value" in sidebar to a value less than the maximum value on a graph
2. Look at the graph

### Expected behavior:
I expected the values on the y-axis to continue up and to the right but instead they plateau. 

### What I got instead:
(screenshots if applicable)
![image](https://user-images.githubusercontent.com/1069047/77469342-4d4c3600-6de5-11ea-8478-7e80faa3cb8c.png)

**Comment by nickcanz** [comment]
@mdbecker to explain this, when setting an axis limit there's two options, you can clip or clamp: https://altair-viz.github.io/user_guide/customization.html#adjusting-axis-limits

This is the "clamp" behavior, the idea is to show there there *is* more data, but leave it at where the axis limit is yet.

The "clip" behavior would be to just cut off the data points when they exceed the limit.

This would be easy to change, let me know! Here's my localhost with the "clip" behavior.

<img width="766" alt="Screen Shot 2020-03-24 at 16 29 18" src="https://user-images.githubusercontent.com/153020/77473957-a8355b80-6dec-11ea-82cc-459eaf6e604f.png">

**Comment by kmid5280** [comment]
I'll give this one a try.
