### ISSUE TITLE
["bug"]

### ISSUE THREAD

**Issue by dzak1234** [CodeForPhilly/chime#229]
Quick question: At any time step, why doesn't the SIR model add up to the total regional population?

**Comment by donovanrichardson** [comment]
On day 0/week 0, for example, the whole regional population is indicated as "susceptible" even though a number are already infected. After that, the sum of susceptible and infected, without recovered, is still greater than the regional population. On day 7 / week 1 this is still true in this screenshot.
<img width="1248" alt="Screenshot 2020-03-24 17 15 31" src="https://user-images.githubusercontent.com/50427582/77477858-68be3d80-6df3-11ea-8965-080a0a3ba3bc.png">

**Comment by dzak1234** [comment]
Thank you. I am new to this website so forgive my questions. I understand. Thank you very much. Could I ask you what time step you used in the model?     On Tuesday, March 24, 2020, 04:25:01 PM CDT, donovanrichardson <notifications@github.com> wrote:  
 
 


On day 0/week 0, for example, the whole regional population is indicated as "susceptible" even though a number are already infected. After that, the sum of susceptible and infected, without recovered, is still greater than the regional population. On day 7 / week 1 this is still true in this screenshot.

**Comment by donovanrichardson** [comment]
@dzak1234 I'm wondering just like you why the numbers don't add up. I'm also new here, and I'm not sure how future cases are projected. I have no idea whether this kind of calculation is intentional or not.

When you look at the app and choose the SIR option without changing anything, what appears on your screen is similar to my screenshot, right? And the numbers don't seem to add up?

**Comment by PhilMiller** [comment]
See #211 - it's about the model's initial conditions. Currently, the Regional Population input is interpreted as the Susceptible population, and the Infected population implied by current hospitalizations are in addition to that. Negligible when case counts were small, not so much now.

When I dug into that, I confirmed that at least the sum of S+I+R was constant over the run.

**Comment by dzak1234** [comment]
That makes sense. Thank you. I am trying to recreate the sir model in excel and I get weird results (attached). I calculated all the inputs (beta, R0, etc), based off of the website's definitions, but for the life of me, cannot get reasonable numbers. Does anyone have any experience with this and may provide insight into what is wrong with my excel calculations?

Thank you very much in advance.
Diana     On Tuesday, March 24, 2020, 05:56:36 PM MDT, Phil Miller <notifications@github.com> wrote:  
 
 


See #211 - it's about the model's initial conditions. Currently, the Regional Population input is interpreted as the Susceptible population, and the Infected population implied by current hospitalizations are in addition to that. Negligible when case counts were small, not so much now.

When I dug into that, I confirmed that at least the sum of S+I+R was constant over the run.

**Comment by donovanrichardson** [comment]
@dzak1234 I think the issue tracker doesn't support attachments, and I can't see them. I'm not sure of who to ask about your particular question, especially since it doesn't seem to be an issue with the CHIME app; in any case, this issue page will probably be closed soon as it is a duplicate. If you check [here](https://code-for-philly.gitbook.io/chime/) there might be some useful information.

**Comment by dzak1234** [comment]
Thank you for replying!     On Wednesday, March 25, 2020, 08:42:32 AM CDT, donovanrichardson <notifications@github.com> wrote:  
 
 


@dzak1234 I think the issue tracker doesn't support attachments, and I can't see them. I'm not sure of who to ask about your particular question, especially since it doesn't seem to be an issue with the CHIME app; in any case, this issue page will probably be closed soon as it is a duplicate. If you check here there might be some useful information.

**Comment by PhilMiller** [comment]
The model has since been adjusted to maintain Population = S + I + R at all time steps, though displayed numbers may deviate slightly due to rounding.
