### ISSUE TITLE
["bug"] Chart tooltip and chart description use different rounding

### ISSUE THREAD

**Issue by pjhoberman** [CodeForPhilly/chime#237]
### Description:
The tooltip (when you hover over a dot on the chart) rounds the number, whereas the description underneath the chart that shows the max value uses a ceiling (rounds up). This can cause a discrepancy between the two values. 

### Steps to reproduce:
1. Increase "number of days to project" to where the chart shows the lines decreasing again
2. Hover over the peak dot and observe the value
3. Compare that value to the description below the chart

### Expected behavior:
The numbers should be the same

### What I got instead:
![image](https://user-images.githubusercontent.com/37924/77491491-86939e80-6e03-11ea-9539-54557b4a8331.png)

In fixing this, please add a test that confirms these numbers are the same, if possible.

Note: There is also an off-by-one issue (#239), but that is why the screenshot shows different days for the peak

**Comment by donovanrichardson** [comment]
I'll try this as a first issue!

**Comment by donovanrichardson** [comment]
The new rounding on my fork moves the peak ahead by a day or two. I don't think this should be a big deal, but I want to point it out anyway.

<img width="1205" alt="image" src="https://user-images.githubusercontent.com/50427582/77569052-f9525780-6e9f-11ea-849d-e40fd777d1b9.png">

In any case, I think it's a little weird that the current version, there's a difference between the peak day in the blurb at the bottom (344 on day 62) and the peak day on the graph (343 on day 61).

**Comment by donovanrichardson** [comment]
> The new rounding on my fork moves the peak ahead by a day or two. I don't think this should be a big deal, but I want to point it out anyway.
> 
> <img alt="image" width="1205" src="https://user-images.githubusercontent.com/50427582/77569052-f9525780-6e9f-11ea-849d-e40fd777d1b9.png">
> 
> In any case, I think it's a little weird that the current version, there's a difference between the peak day in the blurb at the bottom (344 on day 62) and the peak day on the graph (343 on day 61).

Is there a reason why the peak calculation in `chart_descriptions` in `charts.py` adds 1 to the peak day?

**Comment by pjhoberman** [comment]
That bug is here, FYI: https://github.com/CodeForPhilly/chime/issues/239

And I think the +1 was due to a 0-index concern from idxmax, but if it make sense to remove, remove!
