### ISSUE TITLE
export dash as pdf

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/chime#25]
Allow users to export dash outputs (graphs and text) as a pdf report.

**Comment by quinn-dougherty** [comment]
so, streamlit doesn't support csv download of dataframes https://github.com/streamlit/streamlit/issues/400 

**individual charts can be downloaded**. near the upper right hand corner of each chart is a `...`-looking button that offers png, svg download... 

don't get your hopes up too much about exporting to pdf. but i think you can hack it by exporting to html as an intermediary? https://github.com/streamlit/streamlit/issues/297 haven't read this issue too closely myself yet

**Comment by themightychris** [comment]
I maintain this NPM CLI that might be helpful https://github.com/JarvusInnovations/puppeteer-cli

**Comment by sam-qordoba** [comment]
If we are considering headless chrome -> PDF, it is worth mentioning that per https://github.com/streamlit/streamlit/pull/566 , using the browser's print function to save a PDF works pretty well with streamlit. It's not perfect, but if you close the sidebar first, it mostly looks good
![image](https://user-images.githubusercontent.com/47401552/76926818-8b53d200-689a-11ea-9a17-fdcaf3f7fc6c.png)

**Comment by themightychris** [comment]
is there any way to embed a custom CSS stylesheet in Streamlit? If so, we could sprinkle in some print media rules to tweak what the chromium->PDF result looks like, e.g. hide sidebar, adjust spacing, etc

**Comment by sam-qordoba** [comment]
> is there any way to embed a custom CSS stylesheet in Streamlit? If so, we could sprinkle in some print media rules to tweak what the chromium->PDF result looks like, e.g. hide sidebar, hide interactive controls, adjust spacing, etc

AFAICT "yes*" 
* very crudely, e.g.

```
hide_menu_style = """
        <style>
        #MainMenu {visibility: hidden;}
        </style>
        """
```

**Comment by selahlynch** [comment]
I'm going to attempt this one...

**Comment by selahlynch** [comment]
One approach - pure frontend javascript - however it seems to be impossible to add custom javascript to a streamlit app :/ 
https://github.com/streamlit/streamlit/issues/969

**Comment by sam-writer** [comment]
@selahlynch reading [this SO question](https://stackoverflow.com/questions/58795731/how-to-send-data-to-streamlit-from-javascript) I get the feeling that you can jam some JS in there, but it doesn't interact with streamlit. What was the JS solution you were thinking of?

Similar to how we add raw CSS [here](https://github.com/CodeForPhilly/chime/blob/develop/penn_chime/presentation.py#L6), could we add JS in a similar way? EDIT: we actually add the HTML [here](https://github.com/CodeForPhilly/chime/blob/develop/app.py#L40), the previous link defines the HTML that is added

**Comment by themightychris** [comment]
Well if we're using Puppeteer to generate the PDF, we can arbitrarily manipulate the page or inject code at that layer. So for changes we want to make only in print, we don't really need to figure out how to add them into Streamlit since we only need them present during the printing session in our backend.

To use puppeteer, we could either develop our own NodeJS app within the repo, or use the CLI wrapper I maintain which has a maybe-ready-to-merge PR open already to add an --inject-js CLI flag: https://github.com/JarvusInnovations/puppeteer-cli/pull/13

**Comment by sam-writer** [comment]
@themightychris regardless of NodeJS or CLI, won't this need to be a separate process that runs on demand? Or are you thinking of calling to the CLI via python's `os` module?

**Comment by themightychris** [comment]
I don't know the state of Python->puppeteer(or other) bindings. But shelling out to a node process is def an option, and puppeteer (via node) offers the deepest + cleanest interaction with Chromium engine I've ever seen

FYI over in #116 I think we just tested your question @sam-qordoba about can we embed JS that way and it seems that it does not work.  See also https://github.com/streamlit/streamlit/issues/969

So if we need to inject JS for print, it seems like the only option may be from the client-side (i.e. via puppeteer)

**Comment by sam-writer** [comment]
there is the most absurd workaround provided in [this thread](https://discuss.streamlit.io/t/are-you-using-html-in-markdown-tell-us-why/96/25)

> I am still wondering about a temporary workaround. So far, I need to run a separate local python server to access the visualisation htmls (because of the browser’s same-origin policy). Would it be possible for me to copy the vis-htmls to the local streamlit folder, in order to access them from the same port as streamlit (8501 for instance)?
> 
> EDIT: Found the static html folder, I’ll just symlink my generated htmls inside it for the time being. It’s a bit of a sketchy workaround, but it’s okay for now! Being able to embed js in streamlit at some point would be awesome!
> 
> Nice hack workaround! You could also copy your JS/CSS into that folder from within Python, so anyone running your app would get the hack for free.
> 
> For that, you’d have to find the root folder for Streamlit by using os.path.dirname(st.__file__)

My understanding is:
1. Streamlit builds static HTML and puts them... somewhere findable
2. We write code to put the JS/CSS we need in the same place
3. We write markdown containing HTML that points to the files

:sob:

**Comment by sam-writer** [comment]
I was thinking more about puppeteer and I don't think it can work, if I'm understanding it right. because the user wants to download the app *in the state it is in, currently, in their browser*. `st` doesn't expose the state in the URL or anything, so we can't transfer that state over to the puppeteer process on the server, AFAICT

**Comment by themightychris** [comment]
Yeah I was thinking about that, we'd need to:

1. capture the state of all the inputs in the client side
2. send it along with the PDF request to some service that will invoke Chromium
3. input the state to the headless version of the app
4. hack up the page as needed for printing

I know we can do 2-4, 1 seems like we're back to needing to inject javascript into Streamlit

So it seems like our best immediate options are:

1. Stick to making the print version as good as we can through injected CSS and print-media selectors, instruct people to use their browser's print function
2. Fork Streamlit
3. Replace Streamlit

**Comment by mariekers** [comment]
Not sure if it'll need to be refactored if we move off of streamlit - don't want any work to go to waste.  Maybe we should pause this until 2.0 is done?  I trust @sam-qordoba 's judgement

**Comment by Mdraugelis** [comment]
Hi team,
This is a great thread.  Could I tag up @mariekers.  An exported report could be really beneficial.  But before you do any more work lets chat.  I have some feedback after presenting reports for the past week.

**Comment by quinn-dougherty** [comment]
i'm closing this and filing a new issue now that we're on Dash. too much discussion here is streamlit-specific
