### ISSUE TITLE
["dash"] export dashboard as pdf

### ISSUE THREAD

**Issue by quinn-dougherty** [CodeForPhilly/chime#251]
### Description:
export dashboard as pdf

Mike D wrote on the previous issue where this was discussed: 
> . An exported report could be really beneficial. But before you do any more work lets chat. I have some feedback after presenting reports for the past week.

**Comment by Zedmor** [comment]
Plan to work on it

**Comment by themightychris** [comment]
There's a lot of discussion on this already in #25
