### ISSUE TITLE
["model"] Add a warning if reporting detection rate >100%

### ISSUE THREAD

**Issue by PhilMiller** [CodeForPhilly/chime#264]
### Summary

If the number of Known Cases is great than the estimate of Infected based on Current Hospitalization, Market Share, and Hospitalization Rate, then the presented Detection Rate will be greater than 100%. I think we take for granted that Market Share should be a reasonably accurate input. Thus, seeing a condition like that implies that the provided Hospitalization Rate is higher than reality. In that case, the model would predict worse case loads than the data are telling us to expect.

### Suggested fix
Add a notice on Detection Rate > 100% indicating that market share should be double checked, and hospitalization rate may need to be lowered.

**Comment by kmid5280** [comment]
What kind of notice would be ideal? Like a pop-up alert, or additional text displayed within the markdown?

**Comment by PhilMiller** [comment]
Probably additional text. But I'm not a user, so someone in contact with them will have to ask.

Also, the same kind of warning would make sense if somehow the implied infected count were greater than the population. That sort of mistake seems more likely.

**Comment by kmid5280** [comment]
@PhilMiller By implied infected count do you mean the current known infections or the total infections calculated?

**Comment by PhilMiller** [comment]
Known infections > population is a straight-up input error, and should be flagged as such - someone probably mis-keyed a digit or something

For the warning, I meant the total infections calculated.
