### ISSUE TITLE
Fix hover text in inputs

### ISSUE THREAD

**Issue by jlubken** [CodeForPhilly/chime#269]
The hover text is inaccurate. For example for a value of 2.5, 'Hospitalization %' states: "Please enter a valid value. The two nearest valid values are 2.001 and 3.001"

I think the text is generated from the step parameter. Which isn't a bad value, but it is being used to generate the misleading text. Any other options we can add to the st.number_input to fix this?

**Comment by kmid5280** [comment]
What would the text ideally say?
