### ISSUE TITLE
["dash"] Mathjax parsing is not enabled in dash

### ISSUE THREAD

**Issue by Zedmor** [CodeForPhilly/chime#293]
### Description:

formatting of scientific notation is missing from the dash. 
![Dash](https://user-images.githubusercontent.com/9255/77813601-3412e600-7080-11ea-9175-2ac7f927bfee.png)

Simplest solution adding mathjax:

https://community.plotly.com/t/mathjax-in-dash/6653/8

[ ] This is something we can copy over from streamlit (screenshots if applicable)

**Comment by jlubken** [comment]
See #428 

I like that capability for latex. May way still need maths for some of the text describing R-naught values and doubling time computed from date_first_hospitalized.

However, we are removing the "more info about this tool". Keeping the tool behavior in sync with the tool text in docs in sync with the docs is hurting the code velocity. Just keeping the docs in sync with the tool's behavior is hard enough.

**Comment by jlubken** [comment]
See #461
