### ISSUE TITLE
["dash"] Add method on CHIME page for users to request features

### ISSUE THREAD

**Issue by ecsmyth** [CodeForPhilly/chime#299]
### Description:
![image](https://user-images.githubusercontent.com/17688672/77825557-495f3300-70c7-11ea-9269-4ea9aed9703a.png)

Could be a simple as a button/link to the dash issue request page on GitHub `https://github.com/CodeForPhilly/chime/issues/new?labels=enhancement,hospital-request&template=dash-feature.md&title[]=User%20Requested`

**Comment by quinn-dougherty** [comment]
i don't think we want our issues to be flooded like that. it's better if they channel in through docs, then slack, then spinning up issues.

**Comment by mariekers** [comment]
Penn had a direct line of communication on the app in the last version and were flooded with emails - just trying to answer the questions with the documentation first.
