### ISSUE TITLE
["dash"] (dependent on issue 302) remove "show tables" functionality

### ISSUE THREAD

**Issue by quinn-dougherty** [CodeForPhilly/chime#303]
### Description:

When 302 is merged, all we want is download of csv option without any option to show table in app. 

reference: https://github.com/CodeForPhilly/chime/issues/302

[ ] This is something we can copy over from streamlit (screenshots if applicable)

**Comment by mariekers** [comment]
Jordan Clark (on slack) was asking for daily data in the table - is that possible here?
