### ISSUE TITLE
[dash] Plus/minus button size

### ISSUE THREAD

**Issue by mishmosh** [CodeForPhilly/chime#310]
### Description:

In the new [Dash prototype](https://chime-dash-prototype.herokuapp.com/), the +/- buttons are about 6x6 pixels, which is unclickably small (screenshot below). Two options:
- Remove them entirely, or
- Make them larger, like from [streamlit](https://chime-dash-prototype.herokuapp.com/)

Seeking input from frequent users of CHIME — do you use the current +/- buttons?

![image](https://user-images.githubusercontent.com/1306020/77831898-4cc6de80-7108-11ea-8a3a-edb4ec52e12f.png)

**Comment by kmid5280** [comment]
I can remove the arrows in Firefox by adding a `"-moz-appearance": "textfield"` value to the input component's style. Having trouble doing it in Chrome though, the arrows will appear if you hover the mouse over the input, and I haven't found a way to disable that. Edge doesn't seem to show any arrows.
