### ISSUE TITLE
[dash] Make favicon transparent

### ISSUE THREAD

**Issue by mishmosh** [CodeForPhilly/chime#313]
### Description:
The favicon that shows up in browser tabs should have a transparent background, not white as currently shown.

Current screenshot:
![image](https://user-images.githubusercontent.com/1306020/77832066-a54aab80-7109-11ea-9d2a-479696b1f515.png)

Here's a .zip with files you can use: [favicon_package_v0.16.zip](https://github.com/CodeForPhilly/chime/files/4397805/favicon_package_v0.16.zip)

**Comment by quinn-dougherty** [comment]
we actually broke the favicon feature altogether while resolving a MC, sorry.

**Comment by vimalamp** [comment]
According to #402 this issue has been fixed. Is there anything else to do?
