### ISSUE TITLE
[dash] Sidebar text formatting & spacing

### ISSUE THREAD

**Issue by mishmosh** [CodeForPhilly/chime#315]
### Description:

Change font sizes and spacing in left sidebar, to make it more efficient to use.

1. Reduce font sizes headers and labels. Suggested:
  - Reduce font size of h5 (font-size: 1rem;)
  - Reduce font size and margin bottom of label (margin-bottom: 0.1rem; font-size: 0.8rem;)

2. Add space and divider between sections, so eyes can scan more easily between sections. Suggested: a gray line that is 30% width of the left sidebar and centered, 1px and #cccccc (mockup below).

3. In "Display Preferences" section, switch the order of "Maximal y-axis value" and "Present results as dates" to group similar input types.

### Mockups

For Part 2:
![image](https://user-images.githubusercontent.com/1306020/77832607-bac1d480-710d-11ea-8c3e-ada8fd59999b.png)

For Part 3:
![image](https://user-images.githubusercontent.com/1306020/77832722-7be04e80-710e-11ea-8c6c-c776f70d1142.png)

**Comment by kmid5280** [comment]
I'll give this one a try.
