### ISSUE TITLE
["dash"] Dash instance defined in app entrypoint

### ISSUE THREAD

**Issue by BrianThomasRoss** [CodeForPhilly/chime#318]
### Description:
Currently the Dash instance is being defined in the same file as the app entrypoint, this can cause several issues particularly circular imports in certain cases, and this may be the cause of other blockers at the moment

Correcting this should be a top priority in my opinion

From the dash user guide:
![image](https://user-images.githubusercontent.com/48453510/77834937-ffa23700-711e-11ea-9754-6a8b80856c28.png)

[ ] This is something we can copy over from streamlit (screenshots if applicable)

**Comment by quinn-dougherty** [comment]
closed in pulls/319
