### ISSUE TITLE
Check math

### ISSUE THREAD

**Issue by jlubken** [CodeForPhilly/chime#321]
Discussion sir function forcing (s, i, r) values to remain above zero in a way that might hide bugs.

Discussions of #273 from @PhilMiller 

I think the right way to say this is:

```python
new_infections = min(s, beta*s*i)
s_n = s - new_infections
i_n = i + new_infections - gamma*i
```

And similar for recoveries

**Comment by quinn-dougherty** [comment]
Phil I gave a quick pass of your algebra-- `s_n` went smoothly enough for half the cases (i made an assumption that 2 cases would co-occur), but `i_n` didn't terminate for any of the 4 cases. 
![IMG_20200328_174520](https://user-images.githubusercontent.com/39039420/77861623-0181fe00-71e4-11ea-9bba-8bb0596742ba.jpg)

were you proposing altering the content, not something with parity?

**Comment by PhilMiller** [comment]
I'm checking the same approach for recoveries

```python
new_infections = min(s, beta*s*i)
s_n = s - new_infections
new_recoveries = min(i, gamma*i)
i_n = i + new_infections - new_recoveries
r_n = r + new_recoveries

#derivation/assessment from here on

max(gamma*i + r, 0) == r + min(i, gamma*i)
assume i, r, >= 0 (people are finite), and gamma > 0 (i.e. that people recover at all)
LHS simplifies to gamma*i + r
gamma*i + r == r + min(i, gamma*i)
gamma*i == min(i, gamma*i)

case: i >= gamma*i
gamma*i == gamma*i -- success

case i < gamma*i
gamma*i == i
Either i == 0, contradicting the hypothesis, or gamma == 1, also contradicting the hypothesis
```

I'll see if I can finish off the proof around i_n accordingly.

**Comment by PhilMiller** [comment]
This implies that we need a hard stop in the model if the implied initial infected (plus recovered if/when they're added) are greater than the total population, because it would violate `s >= 0` up front.

**Comment by PhilMiller** [comment]
For i_n, the equivalence checking holds with the assumption that `0 < gamma <= 1`. The code does bake in that assumption pretty strongly, since `gamma = 1.0 / p.infectious_days`
