### ISSUE TITLE
["dash"] Bootstrap breakpoint for small screens clashes content and sidebar 

### ISSUE THREAD

**Issue by ckoerber** [CodeForPhilly/chime#326]
### Description:

When hitting the `sm` bootstrap breakpoint for responsive rendering, the sidebar clashes with the content. 

Before breakpoint:

![Screen Shot 2020-03-29 at 13 06 30](https://user-images.githubusercontent.com/35035055/77847549-2b282e80-71be-11ea-97f8-c01de0f8ebe5.png)

Smaller than breakpoint:

![Screen Shot 2020-03-29 at 13 06 40](https://user-images.githubusercontent.com/35035055/77847551-2f544c00-71be-11ea-92d3-b7ba12711890.png)

I believe rendering sidebar before content might be reasonable for small screens.
Adjusting the `container` for the `sidebar` and `content` to a `row` might resolve this.

**Comment by BrianThomasRoss** [comment]
Curious if this is still an issue with the changes, am unable to reproduce.
