### ISSUE TITLE
["bug"] Remove "Penn" from "New Admissions" and "Admitted Patient (Census)"

### ISSUE THREAD

**Issue by Mdraugelis** [CodeForPhilly/chime#348]
## Issue:

Remove the reference to **Penn** in the description of **New Admissions** and **Admittted Patient (Census)**

<img width="425" alt="Screen Shot 2020-03-29 at 4 06 37 PM" src="https://user-images.githubusercontent.com/525828/77859427-46ebfe80-71d7-11ea-801b-dec56ff2b38e.png">

and 

Projected number of daily COVID-19 admissions
<img width="443" alt="Screen Shot 2020-03-29 at 4 06 59 PM" src="https://user-images.githubusercontent.com/525828/77859439-5ec38280-71d7-11ea-89e2-a3b7efffd197.png">

## Fix
Update to 
**New Admissions**
Projected number of daily COVID-19 admissions at hospitals

**Admitted Patient (Census)**
Projected census of COVID-19 patients, accounting for arrivals and discharges at hospitals

**Comment by therealthaibinh** [comment]
Would you also want references to Penn removed from the user docs, or leave them in as examples?

**Comment by Mdraugelis** [comment]
Just the output areas specified here.  I scanned the documentation and didn't see anything stick out.

**Comment by jlubken** [comment]
Completed.
