### ISSUE TITLE
["bug"] Error when current date is set to earlier than date of first hospitalized case

### ISSUE THREAD

**Issue by therealthaibinh** [CodeForPhilly/chime#392]
### Description:
There is an error when current date is set to earlier than date of first hospitalized case. The error message replaces all the graphs/text that are usually in the middle of the page. (i.e. sidebar is unaffected)

### Steps to reproduce:
1. Use defaults (including leaving the current date as today)
2. Set the date of the first hospitalized case as tomorrow (as in, one day after the date in step 1)
3.

### Expected behavior:
Fail gracefully; Give me a message that I'm being dumb.

### What I got instead:
(screenshots if applicable)
![image](https://user-images.githubusercontent.com/3888147/77986553-63765c80-72e5-11ea-8131-f5781310ab85.png)

**Comment by ghost** [comment]
I will take a look into this

**Comment by ghost** [comment]
I am having trouble recreating the bug, has this issue been fixed?
