### ISSUE TITLE
`pip install chime` 

### ISSUE THREAD

**Issue by sam-qordoba** [CodeForPhilly/chime#4]
Related to https://github.com/pennsignals/chime/issues/6

Per this [slack message](https://codeforphilly.slack.com/archives/C01080RBV3Q/p1584462431020400), 

>  i was able to compare the model to the Portugal reality (black datapoints: still not enough data but ok). Im still working on it. What I had to do first was to decouple the code from the web-app integration (it has a few dependencies). maybe the core can transformed into a module ( #chime-app maybe?)

> 
![image](https://user-images.githubusercontent.com/47401552/76882672-3c755080-6838-11ea-91bf-f8fdec7d5552.png)

I am going to guess at some desired functionality / API design, please discuss / correct me in the comments:

* Should be able to `pip install chime` or something similar
* Should be able to `from chime import  sim_sir` and model `sir` in code (? Not sure)
* should be able to ...

**Comment by mdbecker** [comment]
Hi @sam-qordoba this is a great idea :-D. @quinn-dougherty actually attempted to do this yesterday but it caused some unexpected instability in the application (errors in the live productions version). I would like this refactor to happen sooner rather than later but I'm afraid this is going to have to wait until we've knocked out some of the issues causing instability in the live version. For now I would suggest work on this in a feature branch but keep in mind that the code base is in a high state of flux right now so this might become quickly overcome by events.

Hope my response helps!!!

**Comment by luminoso** [comment]
Thank you for considering this. For what I saw in the source-code, it can be split into three parts. My suggestion is:

1. `sim_sir` that has the SIR implementation. This module is invoked with a set of initial values. The output is a data-frame (`sir_results` with the values `s`, `i` and `r`) of the computation of the model.

2. `impact_estimator`: computes `icu`, `hospitalized`, `ventilated` (or any other metric) over the `sir_results` data-frame

3. plot package: draws (and outputs) graphs over the `impact_estimator` and `sir_results` data-frames

**Comment by quinn-dougherty** [comment]
i like your thoughts @sam-qordoba  and @luminoso! imo, the model package only needs one _public_ method--- one that hides the following code: 
```
## RUN THE MODEL

S, I, R = S, initial_infections / detection_prob, 0

intrinsic_growth_rate = 2 ** (1 / doubling_time) - 1

recovery_days = 14.0
# mean recovery rate, gamma, (in 1/days).
gamma = 1 / recovery_days

# Contact rate, beta
beta = (
    intrinsic_growth_rate + gamma
) / S  # {rate based on doubling time} / {initial S}

n_days = st.slider("Number of days to project", 30, 200, 60, 1, "%i")

beta_decay = 0.0
s, i, r = sim_sir(S, I, R, beta, gamma, n_days, beta_decay=beta_decay)


hosp = i * hosp_rate * Penn_market_share
icu = i * icu_rate * Penn_market_share
vent = i * vent_rate * Penn_market_share

days = np.array(range(0, n_days + 1))
data_list = [days, hosp, icu, vent]
data_dict = dict(zip(["day", "hosp", "icu", "vent"], data_list))

projection = pd.DataFrame.from_dict(data_dict)
```

you can read my take on that method here https://github.com/quinn-dougherty/chime/blob/refactor/src/model.py#L47

**Comment by quinn-dougherty** [comment]
>     3. plot package: draws (and outputs) graphs over the `impact_estimator` and `sir_results` data-frames

just a note, in https://github.com/pennsignals/chime/pull/58 chart rendering is function calls a la `def some_chart(dat: pd.DataFrame) -> alt.Chart`, so we're well on our way to modularizing that!

**Comment by luminoso** [comment]
The 3c19ef8 example it is still somewhat coupled to a projection. From what I read on slack I saw requests for other kind of projections. Something like this:


```
def sir():
    ...

def sim_sir():
    ....

def project_icu_hosp_ventilated(s,i,r, ratio_icu, ratio_host, ratio_vent):
    
    # compute rations between s,i,r and the ratios
    
    return projections
    
def project_number_of_beds(ratio_beds):
    # example of other possible estimatiors
    
    projections = project_icu_hosp_ventilated(0.5,0.2,0.1)
    
    # just an example
    return sum_of_hospitalized * ratio_beds

def project_other_things(s,i,r, ...):
    ...
```

This way projections (whatever they are) can be invoked over the same s,i,r results.

**Comment by quinn-dougherty** [comment]
w/r/t 
>@quinn-dougherty actually attempted to do this yesterday but it caused some unexpected instability in the application (errors in the live productions version). I would like this refactor to happen sooner rather than later but I'm afraid this is going to have to wait until we've knocked out some of the issues causing instability in the live version.

as per my comment in https://github.com/pennsignals/chime/issues/6#issuecomment-600214043, **any refactor/modularization that doesn't interact w streamlit io/state should be fine**

**Comment by luminoso** [comment]
This is an easy task. I can write this proposal plus a non-breaking a interface with the current implementation. Is the `refactor` branch the one for this task?

**Comment by quinn-dougherty** [comment]
@luminoso  no make a new branch please

**Comment by quinn-dougherty** [comment]
thru various PRs, everything discussed in this issue has been done but pip-installability. 

there's still opportunity for someone to make those final pushes to `pip install chime`

but we're just about fully modularized
