### ISSUE TITLE
["bug"] In tabular data, please just display date not datetime.

### ISSUE THREAD

**Issue by Mdraugelis** [CodeForPhilly/chime#406]
The simulation has meaning on the resolution of days, instead of hour of day MMM DD YYYY HHMM.

Update the time display to show MMM DD (Apr 20)

<img width="553" alt="Screen Shot 2020-04-01 at 12 10 41 AM" src="https://user-images.githubusercontent.com/525828/78098482-3c835d80-73ad-11ea-847d-37d04e6600f3.png">

**Comment by jlubken** [comment]
See #409 as well, this likely isn't only a presentation issue.
