### ISSUE TITLE
["model"] social isolation started earlier than model assumes

### ISSUE THREAD

**Issue by fedhere** [CodeForPhilly/chime#407]
### Summary
If I understand the model implementation correctly the model is run with beta prior to current date and beta_t after, where beta_t is the beta corrected for social isolation (suppression of contact rate). While this may be true in a new pandemic it is not true in this case: isolation started in many places ~2 weeks ago which is when the first cases started to appear

### Additional details
I am pretty sure what I described is true when the model is run with a given doubling time - not so sure that this is also what happens in the optimized model (when given first hospitalization date)

### Suggested fix
beta_t could be used as a default, or linked to a user input date

**Comment by PhilMiller** [comment]
It's being asked for by multiple users, and I need this for #340 anyway, so building it.

**Comment by PhilMiller** [comment]
Implementation note to self: there are subtleties to be accounted for, particularly during fitting, in the relationship between the mitigation date and the first hospitalization date.

**Comment by PhilMiller** [comment]
There's going to be another subtlety in the fitting procedure if the mitigations result in a dip in the census value - the fit could match to a value on either side of such a dip. Initially, I think users will have to use the 'Current Date' setting to line up with a census value from an earlier date that makes it unambiguous.

**Comment by fedhere** [comment]
indeed (reg the implementation note to self) I noticed because earlier versions of the code were giving different fit if given first hosp. date and letting doubling time free and when using the doubling time found by fitting the date of first hosp. So consistency between the results obtained in this two methods is an important test for this. (suggestion: implement as unit test?)

**Comment by jlubken** [comment]
sim_sir_df allows multiple allows for variadic beta, n_days pairs to be passed into the function to represent changes to social distancing policies. However, neither run_projections nor the ui wiring are flexible enough to use this feature at this point.
