### ISSUE TITLE
site title

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/chime#42]
<img width="321" alt="Screen Shot 2020-03-17 at 8 15 06 PM" src="https://user-images.githubusercontent.com/9036553/76913164-94d63d80-688c-11ea-9532-31d3c3a3de6b.png">

gimme dat sweet custom title

@mdbecker @cjbayesian what do you want this called?

**Comment by quinn-dougherty** [comment]
i don't think it can be _too_ custom. i _should_ be able to change the word `app` to `chime`, but i _probably_ can't get rid of the `- Streamlit` don't get your hopes up

**Comment by mariekers** [comment]
@quinn-dougherty I'm going to guess something along the lines of "Penn CHIME"

**Comment by quinn-dougherty** [comment]
to be clear, the fix is to rename `app.py` to `chime.py` -- at least while we're on streamlit.

**Comment by quinn-dougherty** [comment]
closed in https://github.com/CodeForPhilly/chime/pull/279 (for dash, not for streamlit)
