### ISSUE TITLE
["dash"] Pre-release text cleanup

### ISSUE THREAD

**Issue by therealthaibinh** [CodeForPhilly/chime#428]
### Description:

[x] Consistency in capitalized of parameter names would be a nice-to-have. (e.g. we have “Currently Hospitalized COVID-19 Patients” and “Date of first hospitalized case”)

[x] The descriptive text should match the parameter names as closely as possible (e.g. “Region size” vs. “Regional Population” … “Hospitalization rate” vs “Hospitalization %(total infections)“)

[x] Done in #461 Remove "More Info about this tool" and refer to the docs. Also means that we don't need latex since all the Greek symbols have gone wonky (e.g. $$S_{t+1} = (-\beta S_t I_t) + S_t$$)  

[x] In the sidebar: “Enter this date to have chime estimate the initial doubling time” --> Capitalize CHIME

[ ] This is something we can copy over from streamlit (screenshots if applicable)

**Comment by kmid5280** [comment]
@therealthaibinh Regarding the "more info" section, are you suggesting to remove the text that is revealed (with the glitchy characters) and instead give a way for the user to view the docs directly, versus displaying the info on the intro page?

**Comment by jlubken** [comment]
@kmid5280 The menu on the right in dash has a docs link. I think that will be sufficient.

You are correct, we may not need the latex/mathjax renderer when the more about this tool is removed. OTOH it might be nice to use some latex in the description of the sim's output computed parameters: r-naught, etc.

**Comment by jlubken** [comment]
I think we have everything here.
