### ISSUE TITLE
Begin article: "Contributing: Data Analysis"

### ISSUE THREAD

**Issue by themightychris** [CodeForPhilly/chime#43]
Edit [`docs/contributing/data-analysis.md`](https://github.com/CodeForPhilly/chime/blob/master/docs/contributing/data-analysis.md) and then open a PR against [`CodeForPhilly/chime#master`](https://github.com/CodeForPhilly/chime/compare/master...CodeForPhilly:master)

**Comment by mariekers** [comment]
This would be in the gitbook doc - the one for end users

**Comment by rcknplyr** [comment]
@themightychris and @mariekers I took a look at the GitBook User Guide, and don't really see a place there for this section. However, the Developer Guide has a section under 'Contributing' called 'Data Analysis'.

Could either of you articulate what the original intent of this section was in the Developer Guide? I'm unclear on what would be covered in this section.

**Comment by mariekers** [comment]
I think the idea was to help folks who want to contribute to development of the model itself understand how to participate.  Really, the goal is to just send them to slack.

**Comment by BrianThomasRoss** [comment]
Closing in-line with project direction
