### ISSUE TITLE
["model"] Index day fitting against prescribed doubling time ignores mitigation

### ISSUE THREAD

**Issue by PhilMiller** [CodeForPhilly/chime#439]
### Summary

When the user provides a doubling time, and the model estimates a date of first hospitalization based on that and current census, it ignores that mitigation may have changed the curve prior to the forecast date. This is a hangover from when mitigation was always assumed to be implemented on the forecast date.

Originally noted https://github.com/CodeForPhilly/chime/pull/418/files#r402476603

**Comment by mdbecker** [comment]
FYI this is blocking us from pushing out a release.
Without setting the date of social distancing (with current census of 69)
![image](https://user-images.githubusercontent.com/1069047/78929414-5e957380-7a70-11ea-98e2-71670dd1f185.png)


With setting the date of social distancing (a few days in the past)
![image](https://user-images.githubusercontent.com/1069047/78929385-4de4fd80-7a70-11ea-902c-a6ace990171f.png)

**Comment by PhilMiller** [comment]
The fix for this is likely going to make that branch about as expensive to run as the prescribed first admission date is now, since we'll actually need to simulate separate cases for each possible number of days prior to the mitigation date.

**Comment by PhilMiller** [comment]
The fit is never going to be as good as in the prescribed-first-admission case, since we discretize in whole days, but we can get much closer.

**Comment by PhilMiller** [comment]
Fix partially implemented, but I need to constrain it to not match against a past-the-peak date, just like in the other case.

**Comment by PhilMiller** [comment]
Branch `439-doubling-time-fit-mitigation` has the partial implementation. Still need to prevent fitting post-peak, but let me know if there’s something obviously wrong in that piece
