### ISSUE TITLE
Begin article: "Contributing: Operations Support"

### ISSUE THREAD

**Issue by themightychris** [CodeForPhilly/chime#44]
Edit [`docs/contributing/operations-support.md`](https://github.com/CodeForPhilly/chime/blob/master/docs/contributing/operations-support.md) and then open a PR against [`CodeForPhilly/chime#master`](https://github.com/CodeForPhilly/chime/compare/master...CodeForPhilly:master)

**Comment by rcknplyr** [comment]
- @themightychris and @lottspot, What are your thoughts on what should be in this section of the Developer Guide?
- There is an [Operations Support](https://codeforphilly.github.io/chime/contributing/app-dev.html#project-layout) section under "Project Layout" in the "Application Development" section
- Does this cover what was intended?

**Comment by themightychris** [comment]
@dsgit1 the idea with this article and https://codeforphilly.github.io/chime/contributing/data-analysis.html was to build up some onboarding instructions specific to each role

I don't think we've covered that yet, but i'm not sure how much of a priority it needs to be at this point

**Comment by rcknplyr** [comment]
Created a PR that will update the developer documentation for this one.
