### ISSUE TITLE
Import csvs for PPE calculation

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/chime#441]
CSv's needed by PPE calculations will need to be changed somewhat regularly - is it possible to upload them directly through the UI or app without having to redeploy changes?

Penn has a notebook with the csvs/parameters needed defined - will need to be linked here

**Comment by jlubken** [comment]
I think the approach will be to push csvs and parameter settings to the cluster outside of the app through something like Hashicorp Consul. These settings are monitored by the job scheduler. When the files change the app is automatically restarted. The app reads these csvs and settings on startup.

In this way the configurations can change independent of the software release cycle.
