### ISSUE TITLE
Begin article: "Operations: Deploy to Your Own Cluster"

### ISSUE THREAD

**Issue by themightychris** [CodeForPhilly/chime#45]
Edit [`docs/operations/byok8s.md`](https://github.com/CodeForPhilly/chime/blob/master/docs/operations/byok8s.md) and then open a PR against [`CodeForPhilly/chime#master`](https://github.com/CodeForPhilly/chime/compare/master...CodeForPhilly:master)

**Comment by sam-qordoba** [comment]
I think it is worth mentioning for anyone who wants to do a quick and dirty deploy, they can run `docker run --restart always -p 8000:8000 codeforphilly/chime:latest` and the app will be running on localhost:8000 - that may be enough for some teams

**Comment by themightychris** [comment]
Ohh good point! you wanna start a "Operations: Deploy with Docker" article? :-)

**Comment by ludflu** [comment]
I was  going to give this item a shot - but I want to understand: why would a hospital system want to run their own instance, as opposed to just going to https://penn-chime.phl.io/ ? Do we expect other hospital systems to customize Chime, and if so, how?

**Comment by brendanobra** [comment]
I'm also  interested in this one - I have a microk8s "cluster" at home , or could probably also try it on an EKS cluster.  Would helm-izing the deployment have any value?

**Comment by themightychris** [comment]
@brendanobra probably! Are you thinking helm 3? I haven't used it yet but I heard it doesn't require Tiller be set up so that sounds like it could be a great option to add

**Comment by brendanobra** [comment]
@themightychris , correct - no tiller/tiller-namespace/rbac-hell.  We are currently moving to helm3 for my day job, and really liking it.  Shall I create a helm story, or use this one?

**Comment by themightychris** [comment]
I'd say just use this one, it seems like the straightest line to completing this story

**Comment by rcknplyr** [comment]
Closing as this has been open for a while and project has moved along to maintenance mode.
