### ISSUE TITLE
Subscribe to updates field

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/chime#454]
Add a field to subscribe to updates on the dashboard.
Include: email address, name, and affiliation

**Comment by mangalap123** [comment]
I would like to work on this. Can I discuss this with some experts on the topic.

**Comment by therealthaibinh** [comment]
Similar to https://github.com/CodeForPhilly/chime/issues/335

**Comment by MooseQuest** [comment]
Will need to test when preprod is updated with the new release candidate. (https://penn-chime.bus.phl.io)
