### ISSUE TITLE
["dash"] Move graph legend to a different position near the graph

### ISSUE THREAD

**Issue by kmid5280** [CodeForPhilly/chime#465]
### Description: Graph legend may need to be relocated

Any interest in moving the graph legend to a different position? Currently it sits to the right of the graph, which means that on a smaller screen the graph gets smushed and has to compete with the legend for space.

![graph-mobile](https://user-images.githubusercontent.com/35879775/78394867-ab2d0a80-75a9-11ea-8357-2bc46852e404.png)

[ ] This is something we can copy over from streamlit (screenshots if applicable)

**Comment by mangalap123** [comment]
I can do this. Tried changes in local. I moved the legend in the bottom.
Is this OK?
![image](https://user-images.githubusercontent.com/53016895/78400651-205a0900-75c5-11ea-8f00-e23c69f7aadb.png)

**Comment by MooseQuest** [comment]
#468 closes this issue.
