### ISSUE TITLE
Update run for CI test for chime_dash (when testing/release)

### ISSUE THREAD

**Issue by MooseQuest** [CodeForPhilly/chime#478]
Does this need to be updated too @themightychris ?

_Originally posted by @MooseQuest in https://github.com/CodeForPhilly/chime/pull/477_

**Comment by themightychris** [comment]
As long as streamlit and dash apps co-exist in the same codebase, we should probably fork the GH workflows to test both separately

**Comment by MooseQuest** [comment]
@lottspot I believe your new fancy takes care of this. If so, I'll link the PR and close.

**Comment by rcknplyr** [comment]
Closing for now as Chime1.0 is moving into maintenance mode, and initial version of Chime2.0 is focused on Streamlit.
