### ISSUE TITLE
Automate deploying new container to LKE cluster on tag

### ISSUE THREAD

**Issue by themightychris** [CodeForPhilly/chime#48]
Following #47, automate updating the instance on our LKE cluster via the same GitHub Action workflow

**Comment by themightychris** [comment]
7e399985b0a3b21cfb092d64f3400e64ff43b57f adds a `kubectl` command for doing it manually to the docs

**Comment by themightychris** [comment]
Some reading: https://github.com/GoogleCloudPlatform/continuous-deployment-on-kubernetes/blob/master/README.md

**Comment by bharathkkb** [comment]
@themightychris @lottspot if no one has started on this, i can help.

**Comment by themightychris** [comment]
@bharathkkb yes please! Jump in https://codeforphilly.org/chat/chime-ops and say hi so we can coordinate

**Comment by lottspot** [comment]
A PR for this is being finalized in #259

**Comment by MooseQuest** [comment]
This is resolved via #259 closing!
