### ISSUE TITLE
["dash"] Ping Dash team here if help is requested

### ISSUE THREAD

**Issue by emmanuelle** [CodeForPhilly/chime#487]
Hi there, you folks seem to be doing great with Dash, but if there is something on which help or advice is requested regarding Dash, please ping me here and I will also seek advice from my plotly colleagues (I'm a Python dev at plotly, the company which develops Dash).

**Comment by emmanuelle** [comment]
I also recommend posting a message in the "Show and tell" section of https://community.plotly.com/ if you are looking for community volunteers, the forum has quite a lot of traffic including seasoned users.

**Comment by ckoerber** [comment]
Hello @emmanuelle,

Thanks for reaching out and offering help!

Something we hope to address soon and may need help with is the "print dashboard to PDF option" (see PR https://github.com/CodeForPhilly/chime/pull/308 from @Zedmor). To also print the plots which are generated by callbacks, the current approach is running a selenium instance using a chrome driver and utilizing the print function. Parameters are set through a load from url (still in progress as this PR is behind the new callback URL parameter refactor). Do you have suggestions?
