### ISSUE TITLE
["bug"] Update CHIME documentation to point to penn-chime youtube channel

### ISSUE THREAD

**Issue by Mdraugelis** [CodeForPhilly/chime#496]
Update documentation to point to youtube penn-chime channel.  https://www.youtube.com/channel/UCnyDvzLe1LcbcDsGxObUByA 

I suggest adding a topic under "How Do I use it?".

**Comment by mariekers** [comment]
Added here: https://code-for-philly.gitbook.io/chime/purpose/basic-tutorial
