### ISSUE TITLE
["model"] ["bug"] Epi question regarding rate of new infection in SIR model

### ISSUE THREAD

**Issue by wyusuf068** [CodeForPhilly/chime#506]
### Summary

I was looking for clarification as to why you have stated in the [documentation](https://code-for-philly.gitbook.io/chime/what-is-chime/sir-modeling) that the rate of new infection in the SIR model is **`g=βS−γ`** as opposed to **`g=βS`**.

### Additional details

In the SIR model, the number of infected patients is calculated as follows:

**`It+1 = It + βStIt - γIt`** in which **`It`** is the starting number of infected patients, **`βStIt`** is the number of susceptible patients who become infected (i.e. new infections), and **`γIt`** is the number of infected patients who become recovered (i.e. new recoveries). To me this means that the rate of new infections is mediated by **`βS`** and that **`γ`** mediates the rate of new recoveries.

### Suggested fix

Using **`g=βS`** to estimate rate of new infections, which may have implications in estimating doubling time.

**Comment by DougManuel** [comment]
An issue is `γ` is inconsistently defined and mislabelled in parts of the documentation. `γ` is 1/mean infectious period.  In the documentation, please provide reference and rationale for `"γ: the CDC is recommending 14 days of self-quarantine, we'll use γ=1/14)"`. γ is not the maximum period of infectivity or period of illness or symptoms.

**Comment by DougManuel** [comment]
This issue of γ results in a large impact on projected estimates for larger estimates of social distancing (>60%). As social distancing increases, doubling time increases and β becomes more influenced by γ.  

β=(g+γ), therefore β &rarr; y, when g &rarr; 0 (when double-time [Td] increases). Therefore, the concern will not be seen when validating the model on past observed hospitalizations. 

Related, the more commonly-used period of infectivity is 7 days. See issue [#492](https://github.com/CodeForPhilly/chime/issues/492). Changing the period of infectivity does not have a large influence on the β when doubling time is short, but there is a large effect when doubling time decreases.

**Comment by jlubken** [comment]
#533 modifies both the default doubling_time and infectious_days.

**Comment by DougManuel** [comment]
The math is correct and the suggested fix doesn't need to be incorporated. This issue can be closed. 

The default doubling_time and infectious_days fix is a separate issue has been discussed in issue  #492 and elsewhere. The new defaults are an improvement but people would suggest further modifications, as discussed.
