### ISSUE TITLE
Need ability to test code in staging before tagging / push to production.

### ISSUE THREAD

**Issue by rcknplyr** [CodeForPhilly/chime#518]
### Description:
As a developer, I should be able to test my code in a staging environment before tagging / pushing to production

### Potential workflow
1. Branch/fork
2. Code, commit & unit test
3. PR/merge code to most recent baseline in a staging environment
4. Trigger E2E testing and push code to pre-production environment
5. Trigger UAT
6. Tag code and push to production

**Comment by MooseQuest** [comment]
I've created a namespace chime-test manually. Will look to push this further with scripting.

**Comment by mariekers** [comment]
@MooseQuest what kind of scripting do you want to implement here? Can we break it up and give work to other folks?

**Comment by rcknplyr** [comment]
@MooseQuest, closing this out as we are moving into maintenance mode for this repo. We can address this in Chime2.0 repo as it's still a good to-do.
