### ISSUE TITLE
["model"]

### ISSUE THREAD

**Issue by fedhere** [CodeForPhilly/chime#524]
### Summary

using the dashboard, changing the first hospitalization date from 02/02 too 02/01 makes the prediction change completely

### Additional details

<img width="343" alt="Screen Shot 2020-04-09 at 9 19 12 PM" src="https://user-images.githubusercontent.com/1696902/78953753-e6e33b00-7aa7-11ea-8382-3d1005c44558.png">
<img width="819" alt="Screen Shot 2020-04-09 at 9 19 08 PM" src="https://user-images.githubusercontent.com/1696902/78953755-e6e33b00-7aa7-11ea-9bb8-bfd7d2aecfcd.png">
<img width="326" alt="Screen Shot 2020-04-09 at 9 18 33 PM" src="https://user-images.githubusercontent.com/1696902/78953759-e77bd180-7aa7-11ea-9f2c-39aa7589a6ed.png">
<img width="729" alt="Screen Shot 2020-04-09 at 9 18 56 PM" src="https://user-images.githubusercontent.com/1696902/78953756-e77bd180-7aa7-11ea-9bbf-bf97dae4f503.png">

nothing else changed
<img width="319" alt="Screen Shot 2020-04-09 at 9 18 47 PM" src="https://user-images.githubusercontent.com/1696902/78953757-e77bd180-7aa7-11ea-9384-88a0c21c8579.png">
<img width="317" alt="Screen Shot 2020-04-09 at 9 18 42 PM" src="https://user-images.githubusercontent.com/1696902/78953758-e77bd180-7aa7-11ea-9a17-e2f9434a4232.png">

### Suggested fix
I did not look at the code. cant say where the bug was

**Comment by PhilMiller** [comment]
This is fixed in the soon-to-be-released v1.1.3.

**Comment by PhilMiller** [comment]
This is exactly #378. I've confirmed with your exact parameters that the current code does not display this issue.
