### ISSUE TITLE
Update Habitat build to initialize/set 'parameters' env variable

### ISSUE THREAD

**Issue by rcknplyr** [CodeForPhilly/chime#526]
### Description:
App was modified to take in an env variable called 'parameters' that is required for the app to run. Need to update the habitat build to initialize/set this env variable.

### Guidance from Chris on how to resolve:
To update the habitat build we'd need to add a line to do_install https://github.com/CodeForPhilly/chime/blob/develop/habitat/plan.sh#L69 to copy webapp.cfg into ${pkg_prefix}/defaults/ and then add a line to the run hook like export PARAMETERS="{{pkg.path}}/defaults/webapp.cfg"

habitat/plan.sh:69
  cp -pr ${PLAN_CONTEXT}/../src/* "${pkg_prefix}/"

**Comment by mangalap123** [comment]
I will fix this.

**Comment by rcknplyr** [comment]
Thanks @mangalap123! Please update when completed or advise if any questions.
