### ISSUE TITLE
["dash"] add number of Personal Protectivd Equipment (PPE) needed 

### ISSUE THREAD

**Issue by athenaopp** [CodeForPhilly/chime#541]
### Description:

Could you add the  PPEs requirements to the model? That would allow jurisdictions and hospitals to have a good estimate/forecast their PPEs Needs. I think you would need to add:
1. Number of hospitalized persons (not admitted critical care)
2. Number of critical care/intensive care (to include in hospital but not critical care and in home/community) 
Include a field for assumed number of days in care and staff PPE requirements needs (see below)

(Later revision could expand to include first responders, facilities like jails/nursing homes and at home). 

Here is a link for the estimates of PPEs needed per staff member (based on Ebola: couldn’t find one for Covid yet) https://www.cdc.gov/vhf/ebola/healthcare-us/ppe/calculator.html

Here is WHO’s lost of staff/ scenarios PPE requirements: https://apps.who.int/iris/bitstream/handle/10665/331498/WHO-2019-nCoV-IPCPPE_use-2020.2-eng.pdf

[ ] This is something we can copy over from streamlit (screenshots if applicable)

**Comment by rcknplyr** [comment]
@cjbayesian Could you please advise if this is something Penn would like to add to the app?
