### ISSUE TITLE
["bug"] Heroku deployment failed with develop branch (a8c21bc)

### ISSUE THREAD

**Issue by kochizufan** [CodeForPhilly/chime#553]
### Steps to reproduce:
1. Clone develop branch (a8c21bc) and push it to a private repository
2. Deploy the repository to Heroku.
3.

### Expected behavior:
Latest streamlit CHIME should be worked.

### What I got instead:
(screenshots if applicable)
Error is shown.
<img width="715" alt="スクリーンショット 2020-04-15 17 10 03" src="https://user-images.githubusercontent.com/2221431/79358475-329c5580-7f7c-11ea-9d90-5e490ccfff55.png">

**Comment by jlubken** [comment]
For whatever reason Heroku is using the Pipenv.lock file instead of requirements.txt and setup.py. This Pipenv.lock file does not include the penn_chime module itself (and it should).

Perhaps someone more familiar with Pipenv can add this, of Pipenv can be removed from the project so heroku uses the setup.py instead?

**Comment by jlubken** [comment]
I've asked on ops to see if there is a reason I am unaware of to keep pipenv.

**Comment by cshewmake2** [comment]
Another person and I are having the same issue. By modifying the Pipfile and recreating the Pipfile.lock file, I was able to get it to work locally again. However, it still fails on deployment to Heroku.

**Comment by Sabale88** [comment]
@cshewmake2, can you please elaborate on the modification you did? I am running into the same problem in a Conda environment.
I was trying to fix the above bug myself (by just changing the path to the file), but it only starts a chain of other corrections I need to do. It gets to a place where I find there are some missing objects from the validators.py file, and I really can't understand the problem.
I tried to clone the project again yet I'm getting the same problem.
Do you think your solution may solve what I'm experiencing?

**Comment by therealthaibinh** [comment]
@mdbecker and I tried these steps and it seemed to fix the issue. It has to do with Heroku setting the port.
In the `heroku.yml` file, we changed `Dockerfile.dash` to `Dockerfile`
In the `Dockerfile` file, we added the environment variable for a port, and modified the command to run:
`ENV STREAMLIT_SERVER_PORT=$PORT`
`CMD STREAMLIT_SERVER_PORT=$PORT streamlit run st_app.py`
