### ISSUE TITLE
Suggestions regarding input variables

### ISSUE THREAD

**Issue by volker-dicken** [CodeForPhilly/chime#58]
Copied from my input in the web pages feedback page this morning:

Dear Colleagues,

as a mathematician working at a Fraunhofer  institute for digital
medicine in Bremen, Germany,

I take great interest in prognostic model available
http://penn-chime.phl.io/

I like to suggest the following:

[1) .. (suggested to make this open source, obdiously alredy done)]

2) Modify your web page such that critical data such as the doubling
time and ICU % / Ventilation % might be entered as float values,

as changing these value from say 1 to 2 % results in vastly different
predictions and the by now still unknown true values
are likely to be non integer bus small numbers.

For example my current estimate form positive tested case in the 3
Germany's independent city-states (Berlin+Hamburg+Bremen)

for the doubling time for example is 2.2 days, for the whole of Germany
it its 2.9 (considering the official data published by the
Robert-Koch-Institute)

May estimates for these  doubling times is based on  7* log(cases from
last publishes day) / cases(7 days before) / log(2).

We are at a time were social distancing was just started, thus these
numbers might be close to the natural spread rate, but they are strongly linked to testing, availability, usage and rules applied to  who will be tested. 

It is to be hoped strongly, that the doubling times will get well above your probably significantly 
too high default value of 6 days due to  the measures started a few days ago.

I would think 3 day at most 5 day ought to be the default for the doubling time for your web page.
Looking a longer scale worldwide non china data from Johns Hopking on a log scale I see a factor 100 increase in diagnosed cases in little more than 30 day, related to a doubling tome of about 4.7.

3) One might also consider entering these two numbers (last days #
positive tested case / #positively tested cased 7 days before or some other
time delay) instead of a not well possible direct guess for the doubling time stated
as integer input  in your model.

4) At a later time instead of # positive  tested cases the number of
hospital admission related to COVID 19 at two days a few days apart would probably provide more realistic values,  but these are still very few and not well documented publicly in Germany to use the at the current stage.

Best regards

Volker Dicken

**Comment by mariekers** [comment]
We just did some work to allow float values

**Comment by PhilMiller** [comment]
1 and 2 are completely done.

3 and 4 have been addressed by fitting the spread parameter based on the date of first admission and the current hospital census, and by removing testing details from the model entirely.

So, I'm closing this. If you think there's something still to be addressed, please reopen and call it out, or preferably, open a distinct issue for each requested improvement.
