### ISSUE TITLE
Implement python workflow in github actions

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/chime#59]
Add workflow for python [testing](https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions) in actions

**Comment by themightychris** [comment]
A python workflow was already implemented into GitHub actions in #52:

- `pytest` gets run at the end of the `pythonapp` workflow: https://github.com/CodeForPhilly/chime/pull/52/files#diff-7e3bc64c9dd0eb02c0cac6101ee4e286R40
- `test_app.py` was created with a single sample assertion: https://github.com/CodeForPhilly/chime/pull/52/files#diff-dda76c240c44e9a17f6534f1a4065235R4

The TODO at this point is to actually add meaningful tests to `test_app.py`
