### ISSUE TITLE
Add model tests to pytest

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/chime#61]
Implement manual checks done by Penn (@mdbecker will add here) to github actions

Dependent on #59

**Comment by themightychris** [comment]
I renamed the issue, because we don't need anyone to make any changes to "actions" at this point. Actions runs `pytest`, and devs can also run `pytest` on their own, so we really just need people working on pytest at this point

**Comment by sam-qordoba** [comment]
I added a few tests (3 for UI, one for modeling) in #55 , https://github.com/CodeForPhilly/chime/pull/55/files#diff-dda76c240c44e9a17f6534f1a4065235

@themightychris is right, GH Actions calls pytest, which is pretty good about running any files with `test` in the name. So, if people add more tests to that file, or we make a `tests` directory, with module-specific tests in each, they will get run as long as pytest naming conventions are followed.

**Comment by mariekers** [comment]
If possible, make pytests that mimic these manual tests: 

1. Open up the live (production) app at http://penn-chime.phl.io/ 
       Refresh the page to make sure no inputs are cached
2. In a second tab/window run the app locally (e.g. http://127.0.0.1:8000/)
3. Verify one by one that each of the inputs in the sidebar have not moved (unless this was an explicit part of the issue being addressed). If the issue changed the input on purpose, make sure the rest of the inputs are in the same order as they were before
4. Line up the main frame of the app (the right hand side)
5. Go through the live and local version of the app one page at a time, keeping them in line so you can easily see if there are differences.
6. Click all the check boxes and carefully inspect that the results are the same
7. Look at all graphs and verify that the scale on the y-axis matches and that the scale on the x-axis matches. Verify that the values match
8. Look at each of the data tables and verify that the data in the matches
9. Pay special attention to the bold numbers at the top of the app and the various numbers in “Show more info about this tool” section near the top
10. Change the values for “Currently Hospitalized COVID-19 Patients”, “Doubling time before social distancing (days)” and “Number of days to project” (slider on the right hand panel) to new values.
11. Make sure these values are exactly the same in both the live (production) app and in the local app
12. Repeat steps 3-5

**Comment by mariekers** [comment]
May need to be broken out into separate issues - possibly dependent on model refactor to separate from UI

**Comment by mariekers** [comment]
Tests will be implemented in #115
