### ISSUE TITLE
Currently Known Regional Infections parameter confusion

### ISSUE THREAD

**Issue by sam-qordoba** [CodeForPhilly/chime#62]
[A user asked](https://codeforphilly.slack.com/archives/CV4NGQYMP/p1584545062237900)
> When I adjust the "currently known regional infections" parameter, the charts remain unchanged. Is this intended? If so, could someone explain why changing that number wouldn't affect projections?

To which @cjbayesian replied

>It's not a bug but rather a consequence of how we're estimating the actual number of infected individuals. Specifically, we're using the number of hospitalizations and hospitalization rate to compute the number likely infected. We only use the number of confirmed cases in the region to infer the detection rate.
> You're not the only one confused about this.

User responds:

>  Here's the issue: currently known regional infections is all we have, which means that our position on the timeline is <0 (well, its <0 for the model that assumes 1 hospitalization)
> Acknowledging that the information value of known regional infections is dangerously unreliable as an input, the issue I'm facing is a way to keep the feature in the tool for its palliative effects without diminishing the predictive validity of the output
> My (stats-literate) colleague suggested offering a way to use currently known regional infections as a (really bad) estimate of the true proportion of infected people in the population if it could be combined with estimates of the screening rate
> Perhaps people need to check a box to use it that gives a popup warning them "do not use this. Its really bad, you're liable to mislead yourself" so that people fixated on using it can play with it

**Comment by cjbayesian** [comment]
I recommend moving it to the bottom of the sidebar (and changing order of guidance text accordingly).

**Comment by cjbayesian** [comment]
And stressing in the guidance text what it is used for (only for inferring detection rates).

**Comment by jordanclark397** [comment]
I think that would solve our problem specifically at our orgnization. Another possible solution is to have a toggle somewhere: "How do you want to estimate regional infections?". The default is to use current hospitalization rate and if someone flips it they get a pop-up warning that says something to the effect of "don't do this, its unreliable, we recommend using hospitalization rates if it all possible"

**Comment by cjbayesian** [comment]
I like @jordanclark397 's idea. I'm not sure how feasible that is using streamlit. If we can't accomplish the toggle between estimation methods feature until the app is ported to a more flexible framework, then we should at least move the 'Currently Known Regional Infections' input box down to the bottom of the sidebar.

**Comment by jordanclark397** [comment]
@cjbayesian My only concern is the fact that our leadership is still going to be fixated on the fact that known regional infections doesn't influence projections. Again, to be clear, I understand that their intuitions are the real problem here, but its the problem I'm not quite in a position to say "just trust me. Its supposed to be like that". 

All that said, I understand that my failure to persuade our leadership isn't a good argument for providing an option that reduces validity. So, if you all ultimately decide against addressing our unique challenge I totally understand.

**Comment by jlubken** [comment]
We've removed currently known regional infections from the model.
