### ISSUE TITLE
Create Penn Medicine Branding

### ISSUE THREAD

**Issue by Mdraugelis** [CodeForPhilly/chime#63]
Insert white label mast on a webpage.   https://www1.pennmedicine.org/includes_shared/penn-medicine-header.html

With Mast header "Penn Medicine - COVID-19 Hospital Impact Model for Epidemics"
Remove the website title "COVID-19 Hospital Impact Model for Epidemics" since it will appear in the header.

A quick fix can also be to include an image in the top of the sidebar.
![PM_RGB_2C](https://user-images.githubusercontent.com/525828/76987485-a285d480-6919-11ea-9634-6b66d13e06c1.png)

**Comment by mariekers** [comment]
@quinn-dougherty you think you can implement this with a st.image function or some plain ol markdown?

**Comment by cjbayesian** [comment]
Not perfect, but adding:
```
    st.markdown("""
<link rel="stylesheet" href="https://www1.pennmedicine.org/styles/shared/penn-medicine-header.css">

<div class="penn-medicine-header__content">
    <a href="https://www.pennmedicine.org" class="penn-medicine-header__logo" 
        title="Go to the Penn Medicine home page">Penn Medicine</a>
    <a href="Penn Medicine - COVID-19 Hospital Impact Model for Epidemics" class="penn-medicine-header__title">Penn Medicine - COVID-19 Hospital Impact Model for Epidemics</a>
</div>
    """, unsafe_allow_html=True)
```

in `def head()` gets the job done:
![image](https://user-images.githubusercontent.com/1396669/76990585-93555580-691e-11ea-8957-839e82c11821.png)

**Comment by mariekers** [comment]
sweet! looks like you can close this issue easily!
