### ISSUE TITLE
External monitoring

### ISSUE THREAD

**Issue by garysieling** [CodeForPhilly/chime#74]
It might be valuable to have some external monitoring, e.g. have pingdom notify slack if the site goes down (though perhaps low priority given the attention this already has).

**Comment by mariekers** [comment]
@MooseQuest do y'all get alerts if the site is down?

**Comment by MooseQuest** [comment]
We have something ad-hoc setup. I also setup an alerts channel for chime-ops that uses webhooks. I'll be updating that for easy things today, and then slowly building in more comprehensive things.

**Comment by MooseQuest** [comment]
Added monitor for website up to slack chime-ops-alerts

**Comment by MooseQuest** [comment]
This is complete:

https://status.penn-chime.phl.io

Down alerts can be found in the chime-ops-alerts channel.
