### ISSUE TITLE
Fix linter errors

### ISSUE THREAD

**Issue by garysieling** [CodeForPhilly/chime#75]
When I run this command:

```
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
```

I get a bunch of linter errors:

15    E122 continuation line missing indentation or outdented
1     E203 whitespace before ','
1     E225 missing whitespace around operator
5     E261 at least two spaces before inline comment
8     E302 expected 2 blank lines, found 1
3     E303 too many blank lines (2)
6     E305 expected 2 blank lines after class or function definition, found 1
17    E501 line too long (155 > 127 characters)
4     F401 'functools.reduce' imported but unused
107   Q000 Remove bad quotes
1     W391 blank line at end of file
168

The linter doesn't appear to displaying this in the build output right now, so that I consider finding out why it's not failing the build at the same time if possible.

**Comment by sam-qordoba** [comment]
Hey @garysieling , my understanding is that it lints twice, [the first time](https://github.com/CodeForPhilly/chime/blob/master/.github/workflows/pythonapp.yml#L34) strictly, but just as an FYI, [then](https://github.com/CodeForPhilly/chime/blob/master/.github/workflows/pythonapp.yml#L36) with fewer rules, but with `--exit-zero` so that if it hits any failures it fails the build.

**Comment by garysieling** [comment]
Oh yeah, you're right, thanks for pointing that out

**Comment by pjhoberman** [comment]
Is the main ask here just to clean up the codebase so the linter passes, or passes with fewer errors?

**Comment by garysieling** [comment]
Passes, so that it can be more aggressive (the assumption being that will catch some number of defects in the future)

**Comment by pjhoberman** [comment]
Heard. I will try to tackle early this week, but if anyone else wants it first, please have at it.

**Comment by pjhoberman** [comment]
```
(base) PJs-MBP:chime pjhoberman$ flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
0

```
