### ISSUE TITLE
Investigate implementation of GA

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/chime#78]
Can we implement google analytics on top of streamlit?  how can we get visitor data to app?
Does implementing GA tie the repo to one account?

**Comment by themightychris** [comment]
We should do this via #107 . DM me a google account on slack to get added to the GTM container

**Comment by MooseQuest** [comment]
Need to look at this again. The hacky way may work -- but maybe get some thoughts on frontend backend

**Comment by themightychris** [comment]
GTM with GA and TrackJS is now deployed to prod, DM me on slack if you need to be added to GTM or GA accounts
