### ISSUE TITLE
document devops structure

### ISSUE THREAD

**Issue by mariekers** [CodeForPhilly/chime#81]
What has the ops team built?  How does it help the app? 

Make documentation for app stakeholders to show what/why we built what we built

**Comment by garysieling** [comment]
Initial notes (maybe someone can add color to the first item)
- Kubernetes stuff (scaling, logging to elasticsearch)
- Implemented a standard API for scripts for executing the app ("rule them all")
- Parallel ability to deploy to Kubernetes + Heroku so users can pick what they want
- CI - gating of commits for quality checks, construction of docker container of the app

**Comment by themightychris** [comment]
How do we actually want to change the docs though to close this issue? https://codeforphilly.github.io/chime/

Most of this is already touched on. Do we just need to fill some gaps in? Add a new overview page?

**Comment by mariekers** [comment]
@lottspot if we're planning on moving away from development on the app, is this still useful?  Would it be helpful in outlining how cfp hosts projects in the future?

**Comment by rcknplyr** [comment]
Closing this issue in this repo. Content/intent of the issue is valid - let's address in Chime2.0 repo.
