### ISSUE TITLE
Should `N` be removed from `sir`?

### ISSUE THREAD

**Issue by sam-qordoba** [CodeForPhilly/chime#84]
This was a comment from @luminoso on PR #55 but it is really its own issue...

is there any reason to include `N` parameter in `def sir(y, beta, gamma, N):` function @ `models.py`? Because app.py invokes `sim_sir()` and it defaults `N` to `N = S + R + I`. when `sir()` is invoked you just compute always that scale = 1

IMO, `N` should be removed from `sir()` for three reasons:

1. it doesn't belong to the original formula on the wikipedia
2. in the current implementation it is always computing scale = 1
3. scale can be computed outside sir() for whichever function that needs it in the future

CC @cjbayesian @mdbecker

**Comment by jlubken** [comment]
@sam-qordoba I think the point here is to moderate floating point issues. n is computed from the original values of s, i, and r outside the loop or generator.

**Comment by sam-writer** [comment]
Mentioning @luminoso, since I copied his PR comment into this issue

**Comment by luminoso** [comment]
The code changed a lot in the last 12 days since this issue creation. I need to recheck if this issue is still valid.

**Comment by jlubken** [comment]
I'm closing this issue, feel free to reopen if the explanation was unclear.
