### ISSUE TITLE
Set up automated UI testing

### ISSUE THREAD

**Issue by garysieling** [CodeForPhilly/chime#85]
Split this off #60 - 

> I like this suggestion. I think verifying the models and data aren't broken is most important. However, even after the refactor, there is some coupling of logic and presentation (the framework we are using, Streamlit, makes it pretty hard to fully decouple the two). So, if we want to encode the manual testing procedure, I think that sounds like a puppeteer/selenium thing to me. Or even kasaya which seems like it might be a way to get QA help from non-coders.

Something like Cypress/Selenium can potentially serve three separate purposes:
1. Testing areas in streamlit that are hard to test through the provided APIs
2. Regular UI testing (though maybe this is something this project is delegating to streamlit)?
3. Unlocks the potential for a tool that that smoke tests that a deployed app is up and running

**Comment by themightychris** [comment]
I've really enjoyed using Cypress for this, its desktop runner UI is awesome and accessible, and it's got an excellent GitHub action

Example in the field: 
- https://github.com/SlateFoundation/slate-cbl/blob/c15301bc68f4aaea7325d8faefdfefa0a4930446/.github/workflows/cypress-tests.yml#L55
 - https://github.com/SlateFoundation/slate-cbl/tree/c15301bc68f4aaea7325d8faefdfefa0a4930446/cypress/integration

**Comment by garysieling** [comment]
+1 for Cypress. Updated the description

**Comment by themightychris** [comment]
This script shared to inform unit test design, could also be v1 of our end-to-end testing: https://github.com/CodeForPhilly/chime/issues/61#issuecomment-601340421

**Comment by mishmosh** [comment]
First PR is #128.
