### ISSUE TITLE
Test the scripts in "/script" on ubuntu

### ISSUE THREAD

**Issue by garysieling** [CodeForPhilly/chime#86]
Someone reported an issue through slack - "script/server" failed because it called "source", which did not exist in their shell (I tested the original scripts on my mac / bash).

Low priority, but would reduce the fiction onboarding some people.

**Comment by ecsmyth** [comment]
`script/server` fails on Ubuntu . Changing the shebang to `#!/usr/bin/env bash` works and is likely preferable for portability across distributions.
