### ISSUE TITLE
refactor sidebar

### ISSUE THREAD

**Issue by quinn-dougherty** [CodeForPhilly/chime#87]
from the comments in app.py
```# Initialize variables
# these functions create input elements and bind the values they are set to
# to the variables they are set equal to
# it's kindof like ember or angular if you are familiar with those

# TODO: Refactor all the sidebar stuff into a single function/file
```

read my take on it here: https://github.com/quinn-dougherty/chime/blob/refactor/src/sidebar.py 

if you really wanted to, you could try making it one function that returns a n-tuple of `st.sidebar.input(` calls (then destructure that tuple), but i think this is a lot worse than a single function for each `st.sidebar.input(` call.

**Comment by sam-writer** [comment]
@quinn-dougherty I like the idea in general. I agree that each input should have its own function or method. I think that we can parametrize those functions to take `st` as a parameter, rather that having it be a global.

**Comment by quinn-dougherty** [comment]
done https://github.com/CodeForPhilly/chime/pull/154
