### ISSUE TITLE
[dash] Show a version number at the top of the sidebar along with the model change date

### ISSUE THREAD

**Issue by garysieling** [CodeForPhilly/chime#94]
This would be helpful for when people report issues and simple check to verify a deployment happened. 

Could hook into whatever tagging process devops works up.

[x] See streamlit

**Comment by themightychris** [comment]
I've achieved this before by having the build script pass the SOURCE_SHA and SOURCE_TAG into `docker build` as build args, for `Dockerfile` to then set them as `ENV` vars in the container

The trick then is getting the app to display the `$SOURCE_TAG` env var value in the UI. I have no idea how to do that

**Comment by quinn-dougherty** [comment]
>The trick then is getting the app to display the $SOURCE_TAG env var value in the UI. I have no idea how to do that 

i think
```
# $SOURCE_TAG is put in a .env somehow 
import os
from dotenv import load_env
load_env()
SOURCE_TAG = os.get("SOURCE_TAG")
# ... 
st.markdown(f"version number {SOURCE_TAG}")
```

**Comment by machow** [comment]
I wonder if aligning a bit with some python packaging patterns could help keep things clean / predictable?

Some options I can think of...

* treat app.py conceptually as a package. either as a **single-file package**, with a `__version__="X.Y.Z"` variable at the top of `app.py`, or as a **full-on package** like `app/app.py` and `app/__init__.py`. `__version__` defined in `__init__.py`. This could be useful if you move away from streamlit.
* treat app.py as a part of the `penn_chime` package, and add `__version__` to `__init__.py` there.

Here is a common bit of code python package devs use to parse the version for their `setup.py` files...

```python
from setuptools import setup, find_packages

# parse version ---------------------------------------------------------------

import re
import ast
_version_re = re.compile(r'__version__\s+=\s+(.*)')

with open('penn_chime/__init__.py', 'rb') as f:
    VERSION = str(ast.literal_eval(_version_re.search(
        f.read().decode('utf-8')).group(1)))
```

Then, when you bump the version, you also bump it in `__init__.py`, so people who import the package can check what version they're running

**Comment by themightychris** [comment]
We shouldn't need to put it in .env, since under the container deploy it will be globally baked into the system's env

We just need the heroku and local deploys not to crash when it's missing

**Comment by themightychris** [comment]
@machow having the version number inside the repo content makes a lot of things tough, since we have to keep updating the repo content to designate versions instead of just creating git tags. Could those code spots or variables just pull from the environmental value possibly?

**Comment by mariekers** [comment]
Can the version # also be a link to the release notes?

**Comment by cjbayesian** [comment]
Would it be possible to also let users go back to previous versions? Like if they click the version number they get the release notes, but can also scroll back to a previous version interact with that instead?

**Comment by themightychris** [comment]
> Would it be possible to also let users go back to previous versions? Like if they click the version number they get the release notes, but can also scroll back to a previous version interact with that instead?

Possible, yes, but a huge and extremely complicated effort given the nature of this application. Folks with a working knowledge of git can do that running their own local instance

**Comment by jlubken** [comment]
Perhaps use setuptools_scm after we have pip installable app. It has functions to get the version of the code from within setup.py and a different function to the version within the app. We may have to include the .git directory in the docker image. Just the head of the repo should be sufficient.

**Comment by themightychris** [comment]
If version could be read from the .git directory, why not from env vars? We'd need more than the head included to be able to resolve the version string from a tag

It's ideal if we can let the build workflow implementation determine the version string (it already is) and inject it as a build-arg to the Docker build. The Dockerfile can than permanently set it in ENV, or write it into some file if that's easier. We don't want the build workflow determining a version string to tag the image with and the app determining a version string to display through independent logic

Actually I don't see why it couldn't `sed` it into a `.py` file during the image build if there's some barrier to the python code reading it from env

**Comment by jlubken** [comment]
@themightychris I like your the ENV var over the sed option because it leaves the code exactly as it was checked into the repo.

**Comment by jlubken** [comment]
Streamlit currently uses constants.py and a literal in setup.py.

Integrate/fix this when adding the version and link to dash.
