### ISSUE TITLE
Release notes process

### ISSUE THREAD

**Issue by garysieling** [CodeForPhilly/chime#96]
Something like
1. Should releases be gated to have require release notes? This could be something simple like "the release notes md file changed since the last tag"
2. Should maybe be a link in the app somewhere, and/or in the github pages documentation

**Comment by rcknplyr** [comment]
Closing this for Chime1.0 (Streamlit + SIR) implementation. Will look to care for this in Chime2.0 (Streamlit + Bayesian SEIR) implementation.
